### ISSUE TITLE
Not initializing on vscode start

### ISSUE THREAD

**Issue by DarKDinDoN** [junstyle/vscode-php-cs-fixer#10]
Hello,

Each time I start VSCode I need to deactivate this extension and activate it again.
If I don't to that the extension is not working (nothing happens).

No errors appear in the console.

My config :
- OSX High Sierra
- VSCode 1.17.1

```json
"php-cs-fixer.executablePath": "/Users/myname/.composer/vendor/bin/php-cs-fixer",
"php-cs-fixer.onsave": true,
"php-cs-fixer.config": "/Users/myname/.phpcsfixer",
"php-cs-fixer.allowRisky": true,
```

Other extensions installed :
- PHP DocBlocker
- PHP IntelliSense
- PHP Namespace Resolver
- Other extensions not revelant to PHP

Any idea ?
Thanks,

**Comment by junstyle** [comment]
vsc menu : Help->Toggle Developer tools, see the logs
F1 -> php-cs-fixer: fix this file

**Comment by DarKDinDoN** [comment]
Thanks, another extension was causing this issue.
