### ISSUE TITLE
${workspaceRoot} no longer resolves in vscode 1.39

### ISSUE THREAD

**Issue by aLANparty** [junstyle/vscode-php-cs-fixer#101]
Starting with vscode 1.39 the usage of ${workspaceRoot} for plugin settings is no longer working.  The issue looks to be that the contents of `workspace.workspaceFolders[0]` is no longer a path string.  It is now an object like below.

`
{
	uri: {
		$mid: 1,
		external: "file://path/to/project",
		fsPath: "/path/to/project",
		path: "/path/to/project",
		scheme: "file"
	}
}
`

changing extension.js line 37

`this.executablePath = this.executablePath.replace('${workspaceRoot}', workspace.workspaceFolders[0]);`

to either

`this.executablePath = this.executablePath.replace('${workspaceRoot}', workspace.workspaceFolders[0].uri.path);`

or

`this.executablePath = this.executablePath.replace('${workspaceRoot}', workspace.workspaceFolders[0].uri.fsPath);`

fixes the issue for me

**Comment by junstyle** [comment]
thanks, I forgot workspaceFolders[0] is an object. fixed.

**Comment by anderfernandes** [comment]
I was trying to use `${workspaceFolder}` based on a local install of phpcs using composer and I got and error. In developer tools, the `${workspaceFolder}` variable wasn't being resolved and looking at this issue helped me figure out the problem. Using `${workspaceRoot}` resolved my issue, but as a warning, `${workspaceFolder}` [has been deprecated, according to Visual Studio Code's variable reference page](https://code.visualstudio.com/docs/editor/variables-reference).
