### ISSUE TITLE
Cannot get config file to be recognized

### ISSUE THREAD

**Issue by TheOtherRealm** [junstyle/vscode-php-cs-fixer#106]
The documentation on how to use a custom config file is limited.  I am trying to use tabs and not spaces, to get rid of blank lines, and make brackets be on one line.  However, trying to create a config file to do this does not seem to work.

Here are my settings:

	"php-cs-fixer.executablePath": "${extensionPath}\\php-cs-fixer.phar",
	"php-cs-fixer.lastDownload": 1580400452767,
	"php-cs-fixer.rules": "@PSR2",
	"php-cs-fixer.config": "${extensionPath}\\php-cs-fixer-config.php-cs"

```
<?php
return PhpCsFixer\Config::create()
    ->setRules(array(
        '@PSR2' => true,
        'no_multiline_whitespace_before_semicolons' => true,
        'single_quote' => true,
        'binary_operator_spaces' => array(
            'align_double_arrow' => false,
            'align_equals' => false,
		),
        'blank_line_after_opening_tag' => false,
		'blank_line_before_return' => false,
		'no_blank_lines_after_class_opening'=> true,
		'no_blank_lines_after_phpdoc'=> true,
		'no_blank_lines_before_namespace'=> true,
        'single_blank_line_before_namespace' => false,
        'braces' => array(
            'allow_single_line_closure' => true,
        ),
        'no_extra_consecutive_blank_lines' => array(
            'curly_brace_block',
            'extra',
            'parenthesis_brace_block',
            'square_brace_block',
            'throw',
            'use',
        ),
    ))
    ->setIndent("\t")
    ->setLineEnding("\n");
```

**Comment by junstyle** [comment]
you maybe go to https://github.com/FriendsOfPHP/PHP-CS-Fixer, find more infomation.
this extension just a wrapper for php-cs-fixer
