### ISSUE TITLE
Fixer produces error when formatting not required

### ISSUE THREAD

**Issue by mosfetish** [junstyle/vscode-php-cs-fixer#108]
When the document has formatting errors, Format Document fixes without producing an error. When the document does NOT have formatting errors, Format Document pops an error on screen and in the logs.

v0.1.129 on Windows 10 Pro.

Screen error popup:

``Command 'Format Document' resulted in an error.``

Log[extension host] ouput:

```
[2020-03-05 11:11:43.779] [exthost] [error] [junstyle.php-cs-fixer] provider FAILED
[2020-03-05 11:11:43.779] [exthost] [error] undefined
```

Under same circumstances, Format on Save works without popup error but produces same logs error.

**Comment by junstyle** [comment]
**provider FAILED**, I also do not know the reason that cause this issue.
you can disable other extensions and try again.

**Comment by junstyle** [comment]
#113 #105
