### ISSUE TITLE
PHP CS Fixer Plugin not working

### ISSUE THREAD

**Issue by Hamsterkacke** [junstyle/vscode-php-cs-fixer#11]
Hey!

I tried your plugin, installed php cs fixer correctly (Can use it via commandline)

But it won't format my files with your extension. Log from devtools:

` ["fix", "--using-cache=no", "C:\Users\Philipp\AppData\Local\Temp/temp-ystcafynnq.php", "--rules=@PSR2"]`

After that, nothing happens. 

I have the latest php cs fixer version installed and the latest normal VSCode build.

Tanks!

**Comment by junstyle** [comment]
do you have any other logs from devtools, like mine:
`
[Extension Host] Loaded config default from "D:/wnmp/composer/.php_cs". 
 workbench.main.js:sourcemap:28 
[Extension Host] Paths from configuration file have been overridden by paths provided as command arguments. workbench.main.js:sourcemap:28 
[Extension Host]    1) C:\Users\junstyle\AppData\Local\Temp\temp-xvydybx.php

`

**Comment by Hamsterkacke** [comment]
Nope,

only the ones i provided to you.
Disbaled a lot of other plugins to clean up my dev console.

**Comment by junstyle** [comment]
I uploaded a new version, update and check the log again

**Comment by Hamsterkacke** [comment]
Yes! We have a error that should be helpful:

`[Extension Host] Error: spawn /c/Users/Philipp/AppData/Roaming/Composer/vendor/bin/php-cs-fixer ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)`

I go googling, maybe i can fix it by myself. If not, i'll tell you.

**Comment by junstyle** [comment]
ENOENT ,  "/c/Users/Philipp/AppData/Roaming/Composer/vendor/bin/php-cs-fixer " file not exists
set "executablePath" in config

**Comment by Hamsterkacke** [comment]
It is already set:

"php-cs-fixer.executablePath": "/c/Users/Philipp/AppData/Roaming/Composer/vendor/bin/php-cs-fixer",
    "php-cs-fixer.executablePathWindows": "/c/Users/Philipp/AppData/Roaming/Composer/vendor/bin/php-cs-fixer.bat",

File exists, got them with where php-cs-fixer

**Comment by junstyle** [comment]
/c/Users/Philipp/AppData/Roaming/Composer/vendor/bin/php-cs-fixer
to
c:/Users/Philipp/AppData/Roaming/Composer/vendor/bin/php-cs-fixer

**Comment by Hamsterkacke** [comment]
Works, thank you!
