### ISSUE TITLE
If you paste a string, it will break a new line on its own.

### ISSUE THREAD

**Issue by book000** [junstyle/vscode-php-cs-fixer#116]
Hello. Thank you for developing a great extension.

I'm developing PHP with php cs fixer. When you're doing development, you may copy and paste code.  
However, when you paste, a new line is inserted by itself after the paste.  
If you disable php cs fixer, this will not happen.

![CS9wMj8UvQ](https://user-images.githubusercontent.com/8929706/79249574-6e6de700-7eb8-11ea-82fe-7ef2340f9fdd.gif)

Question 1. Is this the intended behavior?
Question 2. How can this behavior be disabled if it is the intended behavior?

The environment is as follows:

- OS: Windows 10 1903 (build 18362.657)
- VSCode version: 1.44.0
- php cs fixer version: 0.1.150
- `php-cs-fixer.executablePath`: `${extensionPath}\\php-cs-fixer.phar`

I am sorry that my English is so bad.
Thank you for developing this extension.

**Comment by junstyle** [comment]
'single_blank_line_at_eof' => false
you can read : https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by book000** [comment]
Thank you for your reply. It went well.
