### ISSUE TITLE
Extension does not support PSR-12

### ISSUE THREAD

**Issue by brandnk** [junstyle/vscode-php-cs-fixer#118]
I want to use PSR-1 and PSR-12 but when I edited the configuration file using both I received a `PHP CS Fixer: php general error`. This did not happened when i tried to use @PSR1 and @PSR2 together. Any ideas on what the issue might be? Thanks!

My settings:
```
{
    "php-cs-fixer.executablePath": "php-cs-fixer",
    "php-cs-fixer.onsave": true,
    "php-cs-fixer.rules": "@PSR1, @PSR12",
    "php-cs-fixer.lastDownload": 1589373973411,
    "[php]": {
        "editor.defaultFormatter": "junstyle.php-cs-fixer"
}
```

**Comment by junstyle** [comment]
@PSR12 ? exist?

https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage

@PSR12 rule not supported

**Comment by 99linesofcode** [comment]
@junstyle do you mean that PHP-CS-Fixer does not currently support PSR-12 at the time of writing and that is the reason you closed this issue?

**Comment by junstyle** [comment]
if you have any faq about php-cs-fixer, please goto https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage

**Comment by junstyle** [comment]
and psr12 added on 2021.1.12  https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/5504668825130afe21387099ff3a078de71b49e5#diff-1023cdf32306b793dc9ea5bce524d66607c84c4ae85b21d84c03fb6b472e5067

i answered on 2020,  ok?
