### ISSUE TITLE
Configuration for locally installed via composer (no phar)?

### ISSUE THREAD

**Issue by gremo** [junstyle/vscode-php-cs-fixer#119]
I share VS Code settings between Windows/Mac/Linux. My project has a locally installed PHP CS Fixer using Composer, `.vscode/settings.json` commited to VCS.

How can I configure the extension in order to make it work in eache environment?

**Comment by junstyle** [comment]
"php-cs-fixer.executablePath": "php-cs-fixer",
    "php-cs-fixer.executablePathWindows": "php-cs-fixer.bat",

**Comment by gremo** [comment]
Hi, thanks for the reply. It's locally installed, not globally. However, this is not working:

```
"php-cs-fixer.executablePath": "vendor/bin/php-cs-fixer",
"php-cs-fixer.executablePathWindows": "vendor/bin/php-cs-fixer.bat",
```

**Comment by junstyle** [comment]
please read the usage first.
executablePath can use ${workspaceRoot} as workspace first root folder path.

executablePath must be a **absolute path (full path)** of php-cs-fixer or can find it from System **PATH** environment. if you installed via composer , please make sure composer bin path in System PATH variable. and maybe need surfix **.bat** on windows system, php-cs-fixer.bat

**Comment by gremo** [comment]
Thanks, it worked! By the way `${workspaceRoot}` is deprecated, that's the reason I din't try to use it 🤕 

Would be hard to make it work without it? Like many other tools, just a relative path.
