### ISSUE TITLE
Doesn't look work with vscodium

### ISSUE THREAD

**Issue by camlafit** [junstyle/vscode-php-cs-fixer#126]
Hello

I've tried to use extension on vscodium and I get this error : 
![Capture d’écran de 2020-08-04 10-17-02](https://user-images.githubusercontent.com/209915/89270607-db5de600-d63b-11ea-88ee-dc5e403e67da.png)

I've uninstalled extension, remove all data on ~/.vscode-oss/extensions/, reinstall, reload vscodium. In all case I get this error.

I can do more test if useful.

Thanks

**Comment by brunob** [comment]
hey @camlafit nice to see you there :)

I've also faced this bug and fixed it by installing the vsx files after downloading it from the original store. This seems to be the same bug we've been facing for php-debug extension cf https://github.com/VSCodium/vscodium/issues/466#issuecomment-687331078

**Comment by camlafit** [comment]
Hello

I confirm install from vsx looks ok. Then doesn't look related to this module itself.
