### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by jasonbaciulis** [junstyle/vscode-php-cs-fixer#127]
I have PHP 7.4 and get this output:

```PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.3.*.```

Please could you add support for 7.4? It's been out for a while now.

**Comment by junstyle** [comment]
if you use the built-in php-cs-fixer.phar, it's will automatic update the phar file, if the php-cs-fixer support php7.4, otherwise you can use yourself php-cs-fixer.phar, configure in the setting file.
