### ISSUE TITLE
onSave and  onSemicolon, doesn't work

### ISSUE THREAD

**Issue by RhRU** [junstyle/vscode-php-cs-fixer#13]
Visual studio code: version 1.18.1
F1-> php-cs-fixer: fix this file works
on brackets works.
but when enableing this:
"php-cs-fixer.onsave": true,
"php-cs-fixer.autoFixBySemicolon": true,
it does absolutely nothing.
note: latest version of php-cs-fixer also installed also via composer

**Comment by junstyle** [comment]
do you mean when onsave it does nothing?
autoFixBySemicolon only formats current line

**Comment by RhRU** [comment]
Absolutley nothing. I know that it ia the current line for semicolon.
Also it ia on two env's

Pozdrav, Marijan Gudelj

**Comment by junstyle** [comment]
it may have conflict with other extensions, you can disable other extensions and test again.

**Comment by RhRU** [comment]
@junstyle you were right.
ftp-simple was causing the issues (https://marketplace.visualstudio.com/items?itemName=humy2833.ftp-simple)
Hope it helps somebody! Ty

**Comment by abhagsain** [comment]
@junstyle I don't want the extension to move bracket { to a new line. 
How do I override this setting?

**Comment by junstyle** [comment]
@abhagsain https://github.com/FriendsOfPHP/PHP-CS-Fixer
