### ISSUE TITLE
Replacing something in multiple files causes this extension to process those and hangs the whole editor

### ISSUE THREAD

**Issue by mkoske** [junstyle/vscode-php-cs-fixer#130]
Replacing something in multiple files causes this extension to process those and hangs the whole editor for a long period of time.
It should process only files that are currently opened.

**Comment by junstyle** [comment]
maybe vscode use partial formatting when replacing the files now, I have published a new version, you can test again!

**Comment by mkoske** [comment]
Thanks for quick response! I'll try the new version!
