### ISSUE TITLE
Fixer not removing some extra whitespaces

### ISSUE THREAD

**Issue by takdw** [junstyle/vscode-php-cs-fixer#131]
I've ran into two issues where the fixer isn't removing all the extra white spaces. For example the code
```php
public function anotherFunction()
    {
        return

        [



            
            'foo' => 'bar',
        ];
    }
```
gets fixed to
```php
public function anotherFunction()
    {
        return

        [

            'foo' => 'bar',
        ];
    }
```
The result I was expecting is
```php
public function anotherFunction()
    {
        return [
            'foo' => 'bar',
        ];
    }
```
Is this normal? Or is there a way to get my desired output?

-----
PHP CS Fixer: 2.16.4 Yellow Bird
VS Code (Linux): 1.50.0

**Comment by junstyle** [comment]
rules:  https://github.com/FriendsOfPHP/PHP-CS-Fixer#rules
