### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by delta1186** [junstyle/vscode-php-cs-fixer#132]
@junstyle I was hoping you might be able to share a quick development workflow.  I was going to look at an issue I am having, but at this point I am not sure if it's an issue with the extension or php-cs-fixer itself.

I am new to extension development.  I started with the quick start guide on vscode website.  After comparing the default templates you can create using the yo code-generator command I was curious if this project is typescript or js?  Also, the template scaffolding does not use webpack and I see you have a web pack file. 

Here is my workflow so far:
1. Forked and cloned your repo
2. Run npm install 
3. F5 to run debugger, opened a test workspace and ran extension on a php file. 

I think that is correct so far, but just not sure when you are using webpack.  Also, how are you building extension for production?  If I was able to resolve the issue I am having, what actions would you like me to take prior to submitting a PR?

Thanks in advance!

**Comment by junstyle** [comment]
just git clone , and then open in vscode, 
npm install or  yarn, install node modules 
then  press `F5` and debug the codes

the webpack just for publishing this extension, pack files.

**Comment by delta1186** [comment]
Perfect that what I was doing. Thanks for the confirmation!
