### ISSUE TITLE
php-cs-fixer:fix commands

### ISSUE THREAD

**Issue by delta1186** [junstyle/vscode-php-cs-fixer#133]
@junstyle I have spent some time digging into the extension today and have a few questions.

1. What is supposed to be the difference between `php-cs-fixer.fix` and `php-cs-fixer.fix2`?

2. In the `php-cs-fixer.fix2` I saw when you call the `fix(filePath)` method it appears it is suppose to allow for '' as a path.  But this throws an unhandled exception inside of `getArgs` method (specifically when `getActiveWorkspacePath` is called).  This is because the only way I found to pass '' for the filePath to `fix` was by calling `php-cs-fixer:fix2` without a file open in the editor.  What is the intent of calling fix without a filePath?  It is suppose to fix all files in the workspace that are not excluded?

**Comment by junstyle** [comment]
package.json:
```
        "menus": {
            "explorer/context": [
                {
                    "when": "resourceLangId == php",
                    "command": "php-cs-fixer.fix2",
                    "group": "php-cs-fixer"
                },
                {
                    "when": "explorerResourceIsFolder",
                    "command": "php-cs-fixer.fix2",
                    "group": "php-cs-fixer"
                },
                {
                    "when": "resourceLangId == php",
                    "command": "php-cs-fixer.diff",
                    "group": "php-cs-fixer"
                }
            ]
        }
```

php-cs-fixer.fix => format the active file.
php-cs-fixer.fix2 => just run php-cs-fix command, it can fix all files in a folder, 

pcf.fix('') => just for a output tip , when user run from commands box,  **F1** => **php-cs-fix: fix**, no file path provided
