### ISSUE TITLE
php-cs-fixer.phar is not downloaded in vscode.

### ISSUE THREAD

**Issue by adil62** [junstyle/vscode-php-cs-fixer#140]
OS: linux mint 18.0
Php version :7.4.13

while runing its showing this message :
`PHP CS Fixer: executablePath not found, please check your settings. It will set to built-in php-cs-fixer.phar. Try again!`

**Comment by junstyle** [comment]
do you config the option: "executablePath ", make sure executablePath is right.
or you can delete the option, and it will use built-in phar
