### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BobyBoebsel** [junstyle/vscode-php-cs-fixer#141]
Plugin does format this way:

if (statement){
 foo;
}

but i want this way:

if (statement)
{
 foo;
}

How can i change?

**Comment by angelidito** [comment]
I would help you, but I have no idea.
Are you sure you want it that way? I mean, I have seen that with no formatter on if/else statements. Only functions and classes, though.

**Comment by junstyle** [comment]
please read the rules: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.18/doc/rules/index.rst
