### ISSUE TITLE
It does not format ";" when typed in the next line

### ISSUE THREAD

**Issue by angelidito** [junstyle/vscode-php-cs-fixer#142]
I think this is a great formatter, but I miss that.

Also, whitespaces between ";" and the previous word are not formatted. Maybe whitespaces of any kind.
It really blows my mind  :(

Here two examples that it won't format:
> ```
> $hello = 'world       ; 
> echo $hello
> ;
> ```

**Comment by junstyle** [comment]
when type ; , only format current line, can't format previous line
