### ISSUE TITLE
Compatibility with PHP-CS-Fixer v3.0.0

### ISSUE THREAD

**Issue by Arzaroth** [junstyle/vscode-php-cs-fixer#148]
PHP-CS-Fixer v3.0.0 was released in early May of 2021.

One change that "broke" the extension was that the configuration files were renamed.

The extension default value for the configuration files is the V2 ones.

This could probably be addressed here :
https://github.com/junstyle/vscode-php-cs-fixer/blob/4e772053a6cfffe59582a21e9eb6acef0a17d9ef/extension.js#L34

One thing I'm wondering is why have a non-empty defaut value for this setting? Doesn't the executable pull the config from the default config files (.php_cs in V2, .php-cs-fixer.php in V3) itself?

**Comment by junstyle** [comment]
this.config is just a attempt to get an existing config file.
if you do not have existing file, will use empty default value.

**Comment by mrtnzagustin** [comment]
Also, i think this should be added to changelog and make it possible to still use v2. Is there a way to "force" vscode to use a specific version of this extension?

**Comment by junstyle** [comment]
the extension still surpport v2, just builtin phar updated to v3.
you can set the path of v2 phar 

version history:
https://marketplace.visualstudio.com/items?itemName=junstyle.php-cs-fixer&ssr=false#version-history

**Comment by PythooonUser** [comment]
Yeah, I stumbled upon that as well. I just added the file name to the config:

![image](https://user-images.githubusercontent.com/13063023/124129025-a80b1d80-da7d-11eb-9b52-0aabf7391904.png)

A simple PR could be introduced here to add it in the line you mentioned above.

**Comment by PythooonUser** [comment]
My bad. This has already been fixed with ef5c384abb4dc7aa19da833b987c988ad992740b.

**Comment by Arzaroth** [comment]
It has been addressed, thus I'll close this.
