### ISSUE TITLE
Cannot find module 'js-beautify' in code-server

### ISSUE THREAD

**Issue by huanghantao** [junstyle/vscode-php-cs-fixer#149]
https://github.com/cdr/code-server

![image](https://user-images.githubusercontent.com/22836925/124580835-19ced700-de83-11eb-91d3-3b2108bc5ae1.png)

**Comment by junstyle** [comment]
you not install extension from marketplace?
your code is not bundled, so you can check existing of the file js-beautify from the dir
/Users/codinghuang/.local/...../node_modules/
