### ISSUE TITLE
Relative Path config file.

### ISSUE THREAD

**Issue by ghedeonn** [junstyle/vscode-php-cs-fixer#15]
Hey i have a situation here. I want to share the Visual Studio Code settings between work, home, multiple places but with different Users. The problem i got is that i cannot use relative path for the config file in the settings.

For example i have:

```"php-cs-fixer.config": "/Users/name1/Coding/php-cs-fix/.php_cs"```
but for work i have this:
```"php-cs-fixer.config": "/Users/name2/Coding/php-cs-fix/.php_cs"```

so if i will use a sync process between those computers i will every time have to update the correct user.

a solution can be to be allowed to use a relative path:
```"php-cs-fixer.config": "~/Coding/php-cs-fix/.php_cs"```

Thanks!
And good job with the extension!

**Comment by junstyle** [comment]
a new version released, you can update.
"~/" as user home directory on os

**Comment by ghedeonn** [comment]
Hmmm strange i have installed this extension last week ... 
and i have tried with the example above and it does not seem to work.

from this
```"php-cs-fixer.config": "/Users/name1/Coding/php-cs-fix/.php_cs",```
to this
```"php-cs-fixer.config": "~/Coding/php-cs-fix/.php_cs",```

but when i use the second one the php-cs-fix does nothing to the file, in contrast with the first one which changes the file (the same file i mean)

I`m i doing something wrong ?

**Comment by junstyle** [comment]
sorry, I made a mistake, and fixed, you can update it now.

**Comment by ghedeonn** [comment]
Yes! it works now.
thank you!
