### ISSUE TITLE
Problem with last line

### ISSUE THREAD

**Issue by MaluNoPeleke** [junstyle/vscode-php-cs-fixer#154]
If my php file ends like the following php-cs-fixer deletes the last two characters:

```
</div>
<?php snippet('footer') ?>
```
Result:
```
</div>
<?php snippet('footer')
``` 
Expected result:
```
</div>
<?php snippet('footer') ?>
```
If I add some comment to the last line everything is working correctly:
```
</div>
<?php snippet('footer') ?>
<!-- Article Image -->
```
Result:
```
</div>
<?php snippet('footer') ?>
<!-- Article Image -->
``` 
How can I fix it?

**Comment by junstyle** [comment]
rules: https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by MaluNoPeleke** [comment]
Are you referring to https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/doc/rules/php_tag/no_closing_tag.rst or which rule? If I would know the rule I could deactivate it because my CMS has all templates files as explained in the first post.
