### ISSUE TITLE
Format of inline if doesn't work

### ISSUE THREAD

**Issue by tlueder** [junstyle/vscode-php-cs-fixer#156]
This
$this->id         = (isset($data['id'])         ? $this->base->parse->parseInt($data['id'])         : null);

becomes
$this->id = (isset($data['id'])         ? $this->base->parse->parseInt($data['id'])         : null);

But it should be this
$this->id = (isset($data['id']) ? $this->base->parse->parseInt($data['id']) : null);

**Comment by junstyle** [comment]
what?

**Comment by junstyle** [comment]
it's ok, i tested,
the rules go to https://github.com/FriendsOfPHP/PHP-CS-Fixer
