### ISSUE TITLE
Error: spawn php-cs-fixer ENOENT

### ISSUE THREAD

**Issue by mtpultz** [junstyle/vscode-php-cs-fixer#16]
Trying to setup php-cs-fixer for VSCode I get this error for `php-cs-fixer v2.8.3` on Windows 10

`["fix", "--using-cache=no", "C:\Users\mtpul\AppData\Local\Temp/temp-xwyqjr.php", "--rules=@PSR2"]`

```
Error: spawn php-cs-fixer ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

My configuration is:

```
// PHP
// "php-cs-fixer.executablePathWindows": "D:\\installs\\php-cs-fixer\\php-cs-fixer-v2.phar",
"php-cs-fixer.onsave": true,
"php-cs-fixer.autoFixByBracket": true,
"php-cs-fixer.autoFixBySemicolon": true,
"php-cs-fixer.formatHtml": true,
```

I originally tried to use `php-cs-fixer-v2.phar`, but for some reason, it can't access the file.

**Comment by junstyle** [comment]
"php-cs-fixer.executablePath":  "D:\\installs\\php-cs-fixer\\php-cs-fixer-v2.phar",
make sure your executablePath is correct

**Comment by mtpultz** [comment]
Thanks!!! Copied the path from file explorer instead of typing it out, which was my issue... sigh :)
