### ISSUE TITLE
php-cs-fixer.executablePath resets to default

### ISSUE THREAD

**Issue by reynoldspaul** [junstyle/vscode-php-cs-fixer#161]
After updating the config php-cs-fixer.executablePath in settings.json, this value keeps getting reset to the default after a few days. 

Default: ${extensionPath}/php-cs-fixer.phar

I am manually updating to: ${workspaceFolder}/vendor/bin/php-cs-fixer

**Comment by RaiserWeb** [comment]
Ah yes, the problem is, in some of my projects this file doesn't exist, so when I save the file, it reverts to the default setting. I personally would rather it didn't auto-revert to the default. At least I know the issue now, thanks for confirming.

**Comment by Sunhat** [comment]
Yes, this is stupid feature

**Comment by ElfSundae** [comment]
Same here 😅 How to fix this?

**Comment by peterkparty** [comment]
Same
