### ISSUE TITLE
Using relative paths in config does not work

### ISSUE THREAD

**Issue by hoermannklaus** [junstyle/vscode-php-cs-fixer#162]
I try to use relative paths in the workspace configuration to set the settings for the following two values
`
    "settings": {
        "php-cs-fixer.executablePath": "./typo3/vendor/bin/php-cs-fixer",
        "php-cs-fixer.config": ".php_cs"
        ....
`
When I use the full path it works. But as this project may be checked out to various folders it is not possible to enter the full path. I also tried to use "${workspaceFolder}" but it does not work.

Any hints why this doesnt work, or how to achieve this?
Thanks

**Comment by Hakihiro** [comment]
Hi,

You could use the `${workspaceroot}` to get the absolute path to your root project then go into your vendor.

In my case I used : `${workspaceRoot}/vendor/bin/php-cs-fixer`

**Comment by hoermannklaus** [comment]
Thanks for your answer. I tried this, and I works. Kind of...

A little bit more about my scenario:
I use a VSC workspace, in which I define the settings for the php-cs-fixer plugin. For the "executablePath" I now use `${workspaceRoot}/typo3/vendor/bin/php-cs-fixer` which points to the executable for php-cs-fixer. So far so good. Everything works fine.

My project has a subfolder in the tree which contains a extension, on which I need to work often. Therefore I do not want to navigate the whole tree in order to access the folder. So I added the subfolder "test_ext" into the workspace folders. It looks like that.
```json
{
    "folders": [
        {
            "name": "PROJECT: test",
            "path": "."
        },
        {
            "name": "EXT: test_ext",
            "path": "typo3/public/typo3conf/ext/test_ext/"
        }
       ]
}
```
Now I can directly jump into this folder from the VSC explorer entry "EXT: test_ext". Great. But now the "php-cs-fixer" does not work anymore for files in the "test_ext" subfolder. 

I think there is some mixing up of paths now. But that is just my guess. Or maybe I do not understand how to achieve this, or misuse the feature in a way not ment to.

Thanks

**Comment by nunoperalta** [comment]
Hey! Seems `${workspaceRoot}` does work!

However, I'm confused as to why `${workspaceRoot}` works, when it's documented that `${workspaceRoot}` is deprecated in favor of `${workspaceFolder}`

https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented

> Why isn't `${workspaceRoot}` documented?
> The variable `${workspaceRoot}` was deprecated in favor of `${workspaceFolder}` to better align with Multi-root Workspace support.

**Comment by hoermannklaus** [comment]
I figured out, that when I use the "folders" section in my workspace file, VSC sees each of these folders as "root" and therefore the paths do not line up anymore. I may stop using the "folders" section in order to use the plugin again.

**Comment by junstyle** [comment]
as you said, it's deprecated, but it can be used.

**Comment by nunoperalta** [comment]
Sorry - what I meant also is that `${workspaceFolder}` doesn't work. That's what I was trying before. Only when I used the deprecated `${workspaceRoot}`, it worked, which is strange to me.
