### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by byteasc** [junstyle/vscode-php-cs-fixer#164]
This is now throwing errors related to PHP 8.1, is there any updates coming?

**Comment by gintsmurans** [comment]
Hi!

+1

**Comment by junstyle** [comment]
do you use builtin phar? restart vscode, will download latest php-cs-fixer.phar

**Comment by byteasc** [comment]
@junstyle I saw it finally said the extension needed a reload and bam, good to go!

Thank you!
