### ISSUE TITLE
Formatting HTML Inserts Tabs Instead of Spaces

### ISSUE THREAD

**Issue by mtpultz** [junstyle/vscode-php-cs-fixer#17]
Is it possible to format the HTML so it uses spaces instead of tabs?  Right now it enters a tab that is equivalent to 2 spaces regardless of other settings and configuration like .editorconfig.  In the config I have `->setIndent('  ')` to be 2 spaces as well.

**Comment by junstyle** [comment]
html indent is deffirent with php's.
use spaces or tab according to the current document's settings, generally show in vsc's status (right bottom).
also you can try some settings, add to your vsc settings
"html.format.insertSpaces": true,
"html.format.tabSize": 4,

**Comment by mtpultz** [comment]
I have `"editor.insertSpaces": true` and `"editor.tabSize": 4` and at the bottom right it says `Spaces: 2`, but I get tabs for only the HTML content of the PHP page.  I couldn't find `"html.format.insertSpaces"` are you using a VSCode package to format HTML outside of what VSCode already does?

**Comment by junstyle** [comment]
"html.format.insertSpaces" has higher priority in this extension.
"editor.insertSpaces" works now.
new version uploaded.
