### ISSUE TITLE
problem with path with space on windows.

### ISSUE THREAD

**Issue by bokunodev** [junstyle/vscode-php-cs-fixer#171]
it can't format if my working directory has `space` in it.

**Comment by junstyle** [comment]
do you mean folder name and file name? but i tested it's ok. so close.

**Comment by bokunodev** [comment]
hi, not folder/project path. but program path.
i installed php using scoop. so the php binary is placed under user home dir, which may contain space.
i put the phar file next to the php.
its happen on my office pc (windows)

**Comment by bokunodev** [comment]
i'm currently doing remote work, i can provide more information once i get back to the office.
