### ISSUE TITLE
php-cs-fixer.exclude not working with format on save 

### ISSUE THREAD

**Issue by jassMarok** [junstyle/vscode-php-cs-fixer#173]
I am trying to exclude a folder from the fixer but format on save still performs the action on these files, my exclude looks like this 
`"php-cs-fixer.pathMode": "override",
    "php-cs-fixer.exclude": [
        "app/Http/folderToExclude/**/*.php",
    ]`

**Comment by junstyle** [comment]
```
"**/app/Http/folderToExclude/**/*.php"
```

**Comment by pimvanderheijden** [comment]
Took me 30 mins of my live to find this. Cool project!

**Comment by gpibarra** [comment]
@junstyle Does it work if I use `"${workspaceFolder}/app/Http/folderToExclude/**/*.php"` instead of `"**/app/Http/folderToExclude/**/*.php"`?
What I actually want is to exclude `"${workspaceFolder}/index.php"` (only in the project root), and not every `"**/index.php"`.
