### ISSUE TITLE
Disappear as formatter. Update 0.2.11

### ISSUE THREAD

**Issue by akinka** [junstyle/vscode-php-cs-fixer#176]
Hello.

In Windows 10. VSCode 1.68.1.

Suddenly the extension is no available as formatter.

Looking for info in console found this error:

Activating extension 'junstyle.php-cs-fixer' failed: Cannot find module 'c:\Users\xxx\.vscode\extensions\junstyle.php-cs-fixer-0.2.11/extension' mainThreadExtensionService.ts:111
Require stack:
- c:\Users\xxx\.vscode\extensions\junstyle.php-cs-fixer-0.2.11\index.js
- c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js

I have tried to reinstall the extension and in a clean workspace but it continues without working.

Any information about?

Thank you very much.

**Comment by akinka** [comment]
I just realized that it is not "Suddenly" That there has been an update to 0.2.11. Downgrade to 0.2.10 and works again.

**Comment by junstyle** [comment]
updated, traive-ci error, but it published a new version...

**Comment by akinka** [comment]
Thank you! It works.
