### ISSUE TITLE
onsave sometimes stops working until I restart VSCode

### ISSUE THREAD

**Issue by ghnp5** [junstyle/vscode-php-cs-fixer#180]
Hi

I have these configs in my workspace settings:

```
		"php-cs-fixer.config": "..\\myrepo\\phpcsfixer.php",
		"php-cs-fixer.executablePath": "${workspaceFolder}\\..\\myrepo\\vendor\\bin\\php-cs-fixer.bat",
		"php-cs-fixer.onsave": true,
		"php-cs-fixer.allowRisky": true,
```

and my phpcsfixer.php:

```
$config = new PhpCsFixer\Config();
return $config
	->setIndent("\t")
	->setLineEnding("\n")
	->setRules([
(...)
	])
	->setFinder(
		PhpCsFixer\Finder::create()
			->exclude('vendor')
			->in(__DIR__)
	);
```

Many times, the "onsave" seems to stop working. If I restart VSCode, it works again, but eventually stops working again.

When it works, I can see an output like:

(if there is something to fix)
```
[
  "fix",
  "--using-cache=no",
  "--format=json",
  "--config=f:\\Files\\Git\\myrepo/..\\myrepo\\phpcsfixer.php",
  "--allow-risky=yes",
  "--path-mode=override",
  "C:\\Users\\myuser\\AppData\\Local\\Temp/myfile.php"
]
{"files":[{"name":"C:\\Users\\myuser\\AppData\\Local\\Temp\\myfile.php"}],"time":{"total":0.104},"memory":14}
```

(if there is not something to fix)
```
[
  "fix",
  "--using-cache=no",
  "--format=json",
  "--config=f:\\Files\\Git\\myrepo/..\\myrepo\\phpcsfixer.php",
  "--allow-risky=yes",
  "--path-mode=override",
  "C:\\Users\\myuser\\AppData\\Local\\Temp/myfile.php"
]
{"files":[],"time":{"total":0.079},"memory":14}
Loaded config default from "f:\Files\Git\myrepo/..\myrepo\phpcsfixer.php".
Paths from configuration file have been overridden by paths provided as command arguments.
```

But when it stops working, there's no output at all, and the issues stay on the file.

Any ideas why? Or where I can check for any errors.

**Comment by bradrogan** [comment]
Same issue for me. I've tried reinstalling, different underlying `php-cs-fixer` implementations, and no luck besides temporarily after restarting, then back to the same behaviour.

**Comment by junstyle** [comment]
open the **developer tools**, can you see some error logs? please upload next time, otherwise i can't find the problem.


if you enable `"php-cs-fixer.onsave": true`, you must make sure `"editor.formatOnSave": false` first

so i think the best way to format code on save, it enables formattingProvider, settings like these:

```
"php-cs-fixer.onsave": false,
"php-cs-fixer.documentFormattingProvider": true,
"[php]": {
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "junstyle.php-cs-fixer"
}
```

you can try

the **onsave** setting is compatible with early versions.

**Comment by ghnp5** [comment]
Hey. Thanks.
I had `"editor.formatOnSave": false` (default, not set), but I've just made the suggested changes above, to see if it improves :)
Regards.

**Comment by bradrogan** [comment]
I tried the settings, and have the same problem. Here are my logs:

```
[Extension Host]% (7) ['fix', '--using-cache=no', '--format=json', '--config=/Users/brogan/dev/engage/.php-cs-fixer.dist.php', '--allow-risky=yes', '--path-mode=override', '/var/folders/mm/yfbq699s13vb9pxk5b92173r0000gp/T/ArraysTest.php']
console.ts:137 [Extension Host] Error: Loaded config default from "/Users/brogan/dev/engage/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.

    at /Users/brogan/.vscode/extensions/junstyle.php-cs-fixer-0.3.1/index.js:76:61517
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
log.ts:307  WARN undefined
```

**Comment by junstyle** [comment]
@bradrogan 
after problem occurred, the logs can still print? or nothing to print on the developer tool console when you saving files

**Comment by ghnp5** [comment]
@junstyle working well so far, for me!
Happy to close this issue.
Thanks!

**Comment by bradrogan** [comment]
@junstyle same here, it seems things are good with your suggestions. Thanks!
