### ISSUE TITLE
Use PSR-12 as default Rule Set 

### ISSUE THREAD

**Issue by iudizm** [junstyle/vscode-php-cs-fixer#181]
Hi @junstyle, wouldn't it be better to change the default value of the rule set to be [`"@PSR12"`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/ruleSets/PSR12.rst) instead of `"@PSR2"` ?

"As of **2019**-08-10 PSR-2 has been marked as **deprecated**. [PSR-12](https://www.php-fig.org/psr/psr-12/) is now recommended as an alternative."

-- https://www.php-fig.org/psr/psr-2/

**Comment by junstyle** [comment]
ok, updated

**Comment by iudizm** [comment]
nice, thanks

**Comment by laurinneff** [comment]
It'd be even better to change it to `@PER`. Right now, PER only contains the PSR12 rules, but since PER is an evolving standard, it's better to have it now already and automatically have new rules be applied as they're added

**Comment by iudizm** [comment]
@laurinneff I agree that `@PER` should be included in the extension as a possible rule set, as it is a great idea to cover the new changes being made to PHP.

But, in my opinion, 'Evolving Recommendations' aren't the best to set as default rules, if you take in consideration that the extension will fix the code following the *current* recommendations.
So I think the default rule set should be the last defined [Standard Recommendations](https://www.php-fig.org/psr/) for coding style

**Comment by junstyle** [comment]
already set to @PER in new version
