### ISSUE TITLE
Format selection not working

### ISSUE THREAD

**Issue by kik-krsk** [junstyle/vscode-php-cs-fixer#186]
I am select function code and choose Format Selection and nothing changes. I get an error
`Files that were not fixed due to errors reported during linting before fixing:`
![Screenshot_20220823_091103](https://user-images.githubusercontent.com/101323028/186053369-294ead17-0c4a-4ab3-ac0d-9d4f8aa1f473.png)

When I choose to format the entire document, everything is o
![Screenshot_20220823_091217](https://user-images.githubusercontent.com/101323028/186053519-5c6bc439-3e35-4452-a5d2-2757624c9b34.png)
k

**Comment by junstyle** [comment]
it's all right, as you said php lint error, so php-cs-fixer can't format the selected code

**Comment by kik-krsk** [comment]
Why is this happening? if i use php intlephense it works

**Comment by junstyle** [comment]
maybe intlephense  do not lint the code, just do formatting: such as add indent, whitespace...

**Comment by kik-krsk** [comment]
How then to use Format Selection ?

**Comment by junstyle** [comment]
you must make the code is right.

above code, not select the 'public'

and other i've no idea
