### ISSUE TITLE
Temp dir should be configurable

### ISSUE THREAD

**Issue by JoelFeiner** [junstyle/vscode-php-cs-fixer#187]
In a shared server environment, whichever user runs php-cs-fixer first will create and own /tmp/php-cs-fixer. Other users will be locked out. It should be possible to set this temp directory in the configuration so that a user-specific override location can be used, or the tempdir should be randomly generated.

**Comment by junstyle** [comment]
a new setting `tmpDir` added, enjoy

**Comment by JoelFeiner** [comment]
Thank you! Much appreciated.
