### ISSUE TITLE
Warning message "Module already loaded" with  version >=0.3.1

### ISSUE THREAD

**Issue by pbquet** [junstyle/vscode-php-cs-fixer#188]
hi,
Formating php works with PHP CS Fixer version 0.2.12 but I have this error message with version >=0.3.1 in vscode output :

```
[
  "C:\\...\\VSCode\\data\\php-cs-fixer-v2.phar",
  "fix",
  "--using-cache=no",
  "--format=json",
  "--config=C:\\...\\VSCode\\data\\.php-cs-fixer.php",
  "--path-mode=override",
  "C:\\Users\\...\\AppData\\Local\\Temp/Test.php"
]

Warning: Module 'zip' already loaded in Unknown on line 0
{"files":[{"name":"C:\\Users\\...\\AppData\\Local\\Temp\\Test.php"}],"time":{"total":1.38},"memory":22}
{}
```

Windows 10, PHP 7.3.15, vscode 1.69.1

Why is it working on previous version and not in 0.3 ?

Thank you very much.

**Comment by junstyle** [comment]
load php extension "zip" twice,
you must check your php.ini, not about this extension
