### ISSUE TITLE
Is there a way to change the PHP path?

### ISSUE THREAD

**Issue by alexciarlillo** [junstyle/vscode-php-cs-fixer#19]
I am trying to disable xdebug when running php-cs-fixer. I found this old issue for Atom: https://github.com/pfefferle/atom-php-cs-fixer/issues/27 and have adjusted to work for the current php-cs-fixer by changing it to:

`/usr/bin/env php -n -dextension=phar.so -dextension=tokenizer.so -dextension=ctype.so -dextension=json.so "$@"`

And saved that to /usr/local/bin/phpx. Now I want to launch php-cs-fixer using it. Is there currently a way to configure this in the extension?

**Comment by junstyle** [comment]
this extension gets php executor from vsc's default "php.validate.executablePath" value.
you can config like this:
"php.validate.executablePath": "/path/of/php/executor"
