### ISSUE TITLE
lastDownload setting is incompatible with settings sync

### ISSUE THREAD

**Issue by noiob** [junstyle/vscode-php-cs-fixer#193]
VS Code's settings sync is complaining that the `php-cs-fixer.lastDownload` between machines, which is natural. Maybe the timestamp and the auto-download setting should be stored separately and the timestamp in localStorage or somewhere else that doesn't get synced

**Comment by junstyle** [comment]
you can unsync the setting,

```json
  "settingsSync.ignoredSettings": ["php-cs-fixer.lastDownload"]
```
