### ISSUE TITLE
PHP version 8.2 

### ISSUE THREAD

**Issue by Khant-Nyar** [junstyle/vscode-php-cs-fixer#197]
i am face with cs-fixer error with php version ,my current php version is 8.2.1 and cs-fixer doen't support that ? 
i follow to ignore with PHP_CS_FIXER_IGNORE_ENV but i can't

./vendor/bin/php-cs-fixer fix -vvv --dry-run --show-progress=dots
PHP needs to be a minimum version of PHP 7.4.0 and maximum version of PHP 8.1.*.
Current PHP version: 8.2.1.
To ignore this requirement please set `PHP_CS_FIXER_IGNORE_ENV`.
If you use PHP version higher than supported, you may experience code modified in a wrong way.
Please report such cases at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer .

**Comment by Vincz** [comment]
Same issue here. Is this extension still supported? I don't see any commit during the past months. 
Thanks!

**Comment by junstyle** [comment]
https://github.com/junstyle/vscode-php-cs-fixer/commit/2ba2b94644a8bf823030f2f83e58e4d517f5cf88
