### ISSUE TITLE
Context menu not showing despite extension being enabled

### ISSUE THREAD

**Issue by zachrattner** [junstyle/vscode-php-cs-fixer#207]
I don't see the php-cs-fixer option to fix a full folder in my right-click context menu:

<img width="282" alt="Screenshot 2023-09-26 at 11 54 48 AM" src="https://github.com/junstyle/vscode-php-cs-fixer/assets/449150/6ae2b237-1e5f-4c41-bf81-3ef9a62d8587">

But the extension is enabled:
<img width="660" alt="Screenshot 2023-09-26 at 11 55 18 AM" src="https://github.com/junstyle/vscode-php-cs-fixer/assets/449150/4e54266b-1b0e-49c3-abf1-887fb97f7c32">

And I tried quitting/reopening VSCode. 

There are no issues in Output:
<img width="791" alt="Screenshot 2023-09-26 at 11 55 52 AM" src="https://github.com/junstyle/vscode-php-cs-fixer/assets/449150/55634bb9-2cfa-4d24-b0c2-48525c5d8cdf">

Any ideas where I can look to troubleshoot next?

VSCode version:
Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d

OS version:
macOS 13.5.2 (22G91)

**Comment by junstyle** [comment]
you installed is not my published extension. please read carefully

**Comment by zachrattner** [comment]
Uggh sorry! Thanks for the assist
