### ISSUE TITLE
Enable php-cs-fixer.rules as json

### ISSUE THREAD

**Issue by G3z** [junstyle/vscode-php-cs-fixer#24]
I know it's is possible to use a `.php_cs` file fot this but nonetheless:
I noticed it's possible to pass more complex rules but the extension expects the rule as a string

this works but it's ugly
```
"php-cs-fixer.rules": "{\"@Symfony\":true,\"array_syntax\":{\"syntax\":\"short\"}}"
```
this doen't work
```
"php-cs-fixer.rules": {
	"@Symfony": true,
	"array_syntax": { "syntax": "short" }
}
```
is it possible to support both simple string (better for "@Symphony") and json for complex example above

**Comment by junstyle** [comment]
support json formatted value. update new version now. enjoy.

**Comment by G3z** [comment]
SO FAST!
![so fast](https://media3.giphy.com/media/lRnUWhmllPI9a/200w.gif?cid=c94812d05a2ffe704c446e6d490c62e8)
