### ISSUE TITLE
PHP CS Fixer: spawn php-cs-fixer ENOENT. executablePath not found.

### ISSUE THREAD

**Issue by NatoBoram** [junstyle/vscode-php-cs-fixer#25]
Well, I did set `"php.validate.executablePath": "D:\\wamp64\\bin\\php\\php7.0.10\\php.exe"`.

In short, this extension doesn't work out of the box.

**Comment by junstyle** [comment]
executablePath is not your php's path, is your php-cs-fixer's path

**Comment by tanftw** [comment]
Just one to let someone which have problem like me, if you've installed php-cs-fixer via Composer, try set `php-cs-fixer.executablePath` and `php-cs-fixer.executablePathWindows` to `php-cs-fixer.bat`  (no need full path since Composer bin dir has already set in system PATH.

**Comment by evertramos** [comment]
I have installed from the VSCode extension and got this same message... and I could not find this .bat file...

**Comment by TheOneDaveYoung** [comment]
You'll have php-cs-fixer.bat if you install via Composer globally:

composer global require friendsofphp/php-cs-fixer

If you're on Windows 10, you'll find the php-cs-fixer and php-cs-fixer.bat files in your composer vendor bin directory which should be something like:

C:\Users\[YOUR USER NAME HERE]\AppData\Roaming\Composer\vendor\bin

Note that the above directory should be in your windows path environment variable so once you install via Composer simply run: php-cs-fixer.bat from a command window or terminal and it'll run.

**Comment by amadeann** [comment]
I also had this issue. To summarize all the steps mentioned above, this worked for me: 

1. Install php-cs-fixer with `composer global require friendsofphp/php-cs-fixer`
2. Add `Composer\vendor\bin` to `PATH` (it should be something like `C:\Users[YOUR USER NAME HERE]\AppData\Roaming\Composer\vendor\bin`
3. Add `"php-cs-fixer.executablePathWindows": "php-cs-fixer.bat"` to your `settings.json`

**Comment by jeversen** [comment]
Great ! Adding the .bat was the fix which made it work on my windows 7 machine.

**Comment by realrashid** [comment]
https://gist.github.com/realrashid/59d0f99ed31103ae44291f3c752240b6

**Comment by realrashid** [comment]
for Windows setup please follow the below Gist!

https://gist.github.com/realrashid/59d0f99ed31103ae44291f3c752240b6

**Comment by Adorable-SkullMaster** [comment]
![screenshot_2](https://user-images.githubusercontent.com/32746859/41734170-ceba2b02-75a3-11e8-8609-39b7a12d95e3.png)
The extension is still throwing me errors.

1. Installed using Composer. Successful.
2. PATH var: `C:\Users\{My Username}\AppData\Roaming\Composer\vendor\bin`
3. Set `"php-cs-fixer.executablePathWindows"`=`"php-cs-fixer.bat"` in `settings`

When I try to Fix the document it throws me 
`PHP CS Fixer: executablePath not found, please check your settings. It will set to built-in php-cs-fixer.phar. Try again!`
I am on Windows 10.

**Comment by amin-ak** [comment]
> Just want to let someone which have problem like me, if you've installed php-cs-fixer via Composer, try set `php-cs-fixer.executablePath` and `php-cs-fixer.executablePathWindows` to `php-cs-fixer.bat` (no need full path since Composer bin dir has already set in system PATH).

it's work

**Comment by mansoorkhan96** [comment]
> Just want to let someone which have problem like me, if you've installed php-cs-fixer via Composer, try set `php-cs-fixer.executablePath` and `php-cs-fixer.executablePathWindows` to `php-cs-fixer.bat` (no need full path since Composer bin dir has already set in system PATH).
Thank you, You just saved my life.

**Comment by realrashid** [comment]
Your Welcome 😊.
