### ISSUE TITLE
VS Code - Not Running and No Feedback At All

### ISSUE THREAD

**Issue by TheOneDaveYoung** [junstyle/vscode-php-cs-fixer#27]
I'm on Windows 10. Installed php-cs-fixer globally via Composer.

The Composer vendor bin folder is in my path and running php-cs-fixer.bat from anywhere works.

In VS Code I've installed the php-cs-fixer extension and set the config option "php-cs-fixer.executablePathWindows" to "php-cs-fixer.bat".

The trouble is the file is not reformatted and there is no feedback in the terminal and no error alert at the top.

Previously when I didn't have the executablePathWindows option set correctly a red alert would pop up telling me php-cs-fixer could not be found.

I'm sure this is something I've neglected to setup in the config file or options PHP file but for the life of me I cannot figure it out. Is there a log file somewhere?

FYI, if I run php-cs-fixer.bat fix FileToFix.php manuall the file is fixed as expected.

**Comment by junstyle** [comment]
vsc menu: 
help->Toggle Developer Tools
see the logs.

**Comment by TheOneDaveYoung** [comment]
So, looking at the console output in the Dev Tools there are no errors I can find. It looks like php-cs-fixer did it's thing but the file is not altered in the least. 

I'd expect something like:

```
function test() {
  return true;
}
```

to be reformatted per PSR-2 to:

```
function test()
{
  return true;
}
```

Here's the console output:
```
[Extension Host]% (4) ["fix", "--using-cache=no", "C:\Users\DAVEYO~1\AppData\Local\Temp/temp-zahwrflvl.php", "--rules=@PSR2"]0: "fix"1: "--using-cache=no"2: "C:\Users\DAVEYO~1\AppData\Local\Temp/temp-zahwrflvl.php"3: "--rules=@PSR2"length: 4__proto__: Array(0) (at PHPCSFixer.getArgs (C:\Users\Dave Young\.vscode-insiders\extensions\junstyle.php-cs-fixer-0.1.54\extension.js:84:17))
console.ts:123 [Extension Host] You are running PHP CS Fixer with xdebug enabled. This has a major impact on runtime performance.
 (at Socket.exec.stderr.on (C:\Users\Dave Young\.vscode-insiders\extensions\junstyle.php-cs-fixer-0.1.54\extension.js:133:21))
console.ts:123 [Extension Host] If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!
 (at Socket.exec.stderr.on (C:\Users\Dave Young\.vscode-insiders\extensions\junstyle.php-cs-fixer-0.1.54\extension.js:133:21))
console.ts:123 [Extension Host] Loaded config default.
 (at Socket.exec.stderr.on (C:\Users\Dave Young\.vscode-insiders\extensions\junstyle.php-cs-fixer-0.1.54\extension.js:133:21))
console.ts:123 [Extension Host]    1) C:\Users\Dave Young\AppData\Local\Temp\temp-zahwrflvl.php

Fixed all files in 7.183 seconds, 12.000 MB memory used
 (at Socket.exec.stdout.on (C:\Users\Dave Young\.vscode-insiders\extensions\junstyle.php-cs-fixer-0.1.54\extension.js:130:21))
```

**Comment by junstyle** [comment]
`console.ts:123 [Extension Host] You are running PHP CS Fixer with xdebug enabled. This has a major impact on runtime performance.
 (at Socket.exec.stderr.on (C:\Users\Dave Young\.vscode-insiders\extensions\junstyle.php-cs-fixer-0.1.54\extension.js:133:21))
console.ts:123 [Extension Host] If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!
`
if 'Socket.exec.stderr.on' executed, this exetension will reject and exit.
so maybe you should disable xdebug in php.ini, and try again.

**Comment by TheOneDaveYoung** [comment]
Okay, disabling xdebug works and the file is formatted as expected, however...

I don't think disabling xdebug is a viable solution as I, like a great many PHP developers, rely heavily on it. What is the conflict here? This xdebug & vs code php-cs-fixer shouldn't be mutually exclusive. Especially considering the file is formatted properly if I run php-cs-fixer.bat fix file.php outside of vs code.

**Comment by junstyle** [comment]
I update a new version, you can try again when you enable xdebug.
https://github.com/junstyle/vscode-php-cs-fixer/commit/5cce22d081a459cf7a25ddf6133394eb89593dde

**Comment by TheOneDaveYoung** [comment]
Okay, I updated to 0.1.55, reloaded VS Code, and re-enabled XDebug in php.ini but it's still not formatting the file in VS Code.  Bummer! :-)

```
[Extension Host]% (4) ["fix", "--using-cache=no", "C:\Users\DAVEYO~1\AppData\Local\Temp/temp-srgunbvv.php", "--rules=@PSR2"]0: "fix"1: "--using-cache=no"2: "C:\Users\DAVEYO~1\AppData\Local\Temp/temp-srgunbvv.php"3: "--rules=@PSR2"length: 4__proto__: Array(0) (at PHPCSFixer.getArgs (C:\Users\Dave Young\.vscode-insiders\extensions\junstyle.php-cs-fixer-0.1.55\extension.js:84:17))
console.ts:123 [Extension Host] You are running PHP CS Fixer with xdebug enabled. This has a major impact on runtime performance.
 (at Socket.exec.stderr.on (C:\Users\Dave Young\.vscode-insiders\extensions\junstyle.php-cs-fixer-0.1.55\extension.js:133:21))
console.ts:123 [Extension Host] If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!
 (at Socket.exec.stderr.on (C:\Users\Dave Young\.vscode-insiders\extensions\junstyle.php-cs-fixer-0.1.55\extension.js:133:21))
console.ts:123 [Extension Host] Loaded config default.
 (at Socket.exec.stderr.on (C:\Users\Dave Young\.vscode-insiders\extensions\junstyle.php-cs-fixer-0.1.55\extension.js:133:21))
```

**Comment by junstyle** [comment]
php-cs-fixer did not pass a right signal, though it formats the file in terminal, but it performs a stderr and not returns a result code.
