### ISSUE TITLE
"Sorry, but there is no formatter for 'plaintext'-files installed." when saving a new PHP-file

### ISSUE THREAD

**Issue by larsnystrom** [junstyle/vscode-php-cs-fixer#29]
Whenever I save a new PHP-file, I see the message "Sorry, but there is no formatter for 'plaintext'-files installed.". If I disable vscode-php-cs-fixer and reloads vscode, the issue disappears, so I'm pretty confident the issue is with this plugin.

- Extension Name: php-cs-fixer
- Extension Version: 0.1.56
- OS Version: Darwin x64 17.3.0
- VSCode version: 1.19.2

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 15,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:php"
	}
}
```

**Comment by junstyle** [comment]
'plaintext'-files ? are you sure your file is php file?

**Comment by larsnystrom** [comment]
Yes, very sure. You should be able to reproduce this by creating a new file (in a new editor tab), writing <?php in it and saving it for example as test.php in any directory.

**Comment by junstyle** [comment]
yes, I tested, no error appeared
os: win10

**Comment by larsnystrom** [comment]
I’ll test it on a Linux machine and see if there’s a problem there. I reported this from a Mac. 

I can also try to disable all other plugins, to see if the problem is because of some combination of this plugin and another one.

I’ll get back to you in a few hours.

**Comment by larsnystrom** [comment]
I disabled all user-installed extensions but php cs fixer, and the issue is still there. Running extensions are still showing emmet, git, merge-conflict and php, but I can't disable those. The issue disappears when I disable php cs fixer.

I also tried it on a linux machine, but I could not reproduce this issue there, so it seems this is Mac specific. 

I have never developed a vscode plugin, but I know some js. Where do you think I should start debugging?

**Comment by junstyle** [comment]
download the codes, F5 debug in vsc
extension.js is main file
