### ISSUE TITLE
Other extensions taking precedence in right-click menu 

### ISSUE THREAD

**Issue by MortimerCat** [junstyle/vscode-php-cs-fixer#3]
I have this extension working well on its own.  Unfortunately, some other extensions also have a formatting option included and the right-click menu is executing. the other extension.  I have to format by going into the command palette.  

The question I want to ask here is "do you know a way I can get the right-click menu to execute the extension I want"?

**Comment by junstyle** [comment]
I had added an option to config whether regiseter php document formatting
provider, you can set registerFormattingProvider to false.

2017-08-11 20:20 GMT+08:00 MortimerCat <notifications@github.com>:
