### ISSUE TITLE
ERROR: PHP CS Fixer: spawn php-cs-fixer ENOENT. executablePath not found.

### ISSUE THREAD

**Issue by KevinBatdorf** [junstyle/vscode-php-cs-fixer#31]
Started happening on both my PC and my Mac probably about a week ago. I couldn't get it to read the path on either no matter what I tried. I updated the $path, tried putting relative paths and absolute paths, tried php-cs-fixer.bat (on Windows). Nothing works.

Any more tips? Thanks

**Comment by junstyle** [comment]
please paste your config
full path if your PATH not contains the php-cs-fixer's path.

**Comment by yogeshkoli** [comment]
@KevinBatdorf - Try this into code user settings:

"php-cs-fixer.executablePath": "/Users/username/.composer/vendor/bin/php-cs-fixer"

And you should be good to go.

**Comment by KevinBatdorf** [comment]
Hey guys, thanks for the feedback. Not sure what changed, but I had just turned it back on now (by `"php-cs-fixer.onsave": true,`) and it's working on my Mac. I'll be able to try on my PC later on tonight. I'll follow up. Thanks

**Comment by mhenkel1** [comment]
Same problem here: Just installed via vs code extensions, restarted vs code.
Same error as soon as you call it...
Not working out of the box, tried @yogeshkoli 's solution, does not work for me either :/

**Comment by realrashid** [comment]
for Windows setup please follow the below Gist!

https://gist.github.com/realrashid/59d0f99ed31103ae44291f3c752240b6

**Comment by mpandzo** [comment]
> Hey guys, thanks for the feedback. Not sure what changed, but I had just turned it back on now (by `"php-cs-fixer.onsave": true,`) and it's working on my Mac. I'll be able to try on my PC later on tonight. I'll follow up. Thanks

As @KevinBatdorf stated, php-cs-fixer setting (either true or false) is needed for this issue to be resolved on Windows 10.
