### ISSUE TITLE
Add Support for more than one php-fig coding standard.

### ISSUE THREAD

**Issue by steven7mwesigwa** [junstyle/vscode-php-cs-fixer#32]
_vscode version:_ v 1.18.1
_php-cs-fixer version:_ PHP CS Fixer 2.10.0 

## Issue:
Am currently using "PSR2" for code fixing, which works fine:
_Current Configuration:_

```
{
...

"php-cs-fixer.rules": "@PSR2"

...
}
```
## Question:
I would like to also enforce "PSR1".
**Qn:** Is it possible to enforce **BOTH** "PSR1" and "PSR2" at ago ?
For example:
`"php-cs-fixer.rules": "@PSR2, @PSR1"`

_Thanks in advance._

**Comment by junstyle** [comment]
rules support json
"php-cs-fixer.rules":{
     "@PSR2": true,
     "@PSR1": true
}
https://github.com/junstyle/vscode-php-cs-fixer/issues/24

**Comment by steven7mwesigwa** [comment]
Thank you so much for  your quick response despite your busy week.
