### ISSUE TITLE
PHP Parse error: syntax error, unexpected '?'

### ISSUE THREAD

**Issue by betaSavvy** [junstyle/vscode-php-cs-fixer#33]
vscode: v1.19.3
php-cs-fixer: homebrew/php/php-cs-fixer: stable 2.10.0 (bottled)

## Issue
Throws these error in the developer tools when I tried to fix the file.

[Extension Host] PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /usr/local/Cellar/php-cs-fixer/2.10.0/vendor/symfony/options-resolver/OptionsResolver.php on line 980
[Extension Host] Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /usr/local/Cellar/php-cs-fixer/2.10.0/vendor/symfony/options-resolver/OptionsResolver.php on line 980

**Comment by junstyle** [comment]
php syntax error, check your file
