### ISSUE TITLE
Support workspace Composer folder

### ISSUE THREAD

**Issue by Dasc3er** [junstyle/vscode-php-cs-fixer#34]
To actively support local Composer installation to find _PHP CS Fixer_, I believe it would be useful to change line 30 of **extension.js** in this way:
```js
this.executablePath = config.get('executablePath', '${workspaceRoot}\vendor\bin\' + process.platform === "win32" ? 'php-cs-fixer.bat' : 'php-cs-fixer');
```

In this way, the plugin should support the workspace Composer folder...

**Comment by junstyle** [comment]
executablePath can use ${workspaceRoot} as workspace root path.
