### ISSUE TITLE
Can not run risky fixers..

### ISSUE THREAD

**Issue by Blum** [junstyle/vscode-php-cs-fixer#37]
Hello,
thanks for the nice extension.

I have a bit of a problem here, I can not make it run risky fixers. If I do it manually: 
`php-cs-fixer fix file.php --allow-risky=yes --rules="psr4"
`
It runs fine (renaming the class according to the file name). But if I run it with VSCode, by setting "php-cs-fixer.allowRisky": true and "'psr4' => true," in .php_cs it does not rename the class.

Am I missing something..?

Thanks

**Comment by junstyle** [comment]
settings:

`    "php-cs-fixer.allowRisky": false`

**Comment by Blum** [comment]
Hello,
I'm not sure I understand.. 
If you want to know if I've set "php-cs-fixer.allowRisky" to true, yes, I have. Still not renaming the class.
