### ISSUE TITLE
php include_once space inserted in associative array key value

### ISSUE THREAD

**Issue by esetnik** [junstyle/vscode-php-cs-fixer#42]
When fixing the following example, an extra space is inserted in the key `$_SERVER['DOCUMENT_ROOT']` so that it becomes `$_SERVER['DOCUMENT_ROOT ']`

Example:
```php
<a href='javascript:void(0);' id='<?php echo $DeptID; ?>' onclick='changeDepartment("<?php echo $DeptID; ?>","<?php echo str_replace("'
  ", "\\ ", $DeptName); ?>  ", "<?php echo $DeptShortName; ?>",
  1, "<?php echo $DeptState ?>"); '>
                            <span class="icon-office"></span><?php echo $Pro_DeptName . ' TO '; ?>
                        </a>
                
<!-- ### BEGIN: Help Modal ### -->
<?php include_once $_SERVER['DOCUMENT_ROOT'] . "/shared/helpModal.php";  ?>
<!-- ### END: Help Modal ### -->
```
Output:
```php
<a href='javascript:void(0);' id='<?php echo $DeptID; ?>' onclick='changeDepartment("<?php echo $DeptID; ?>","<?php echo str_replace("'
  ", "\\ ", $DeptName); ?>  ", "<?php echo $DeptShortName; ?>",
  1, "<?php echo $DeptState ?>"); '>
                            <span class="icon-office"></span><?php echo $Pro_DeptName . ' TO '; ?>
                        </a>
                
<!-- ### BEGIN: Help Modal ### -->
<?php include_once $_SERVER['DOCUMENT_ROOT '] . "/shared/helpModal.php";  ?>
<!-- ### END: Help Modal ### -->
```

**Comment by junstyle** [comment]
onclick='changeDepartment("<?php echo $DeptID; ?>","<?php echo str_replace("'
  ", "\\ ", $DeptName); ?>  ", "<?php echo $DeptShortName; ?>",
  1, "<?php echo $DeptState ?>"); '

this line has unmatched single quote, maybe js-beautify can't parse correctly. I have no idea.
I think you should avoid too complex tags with php code.
you can do like this:
`<?php
echo "<a href='javascript:void(0);' id='", $DeptID, "' onclick='changeDepartment(\"", $DeptID, '","', ........
`

**Comment by esetnik** [comment]
Sorry I don't see the unmatched single quote here

```js
onclick='changeDepartment("<?php echo $DeptID; ?>","<?php echo str_replace("' ", "\\ ", $DeptName); ?> ", "<?php echo $DeptShortName; ?>", 1, "<?php echo $DeptState ?>"); '
```

This is not really unmatched because when the php is rendered it would be removed. But I can confirm that this single quote the cause of the issue.
`<?php echo str_replace("' ", "\\ ", $DeptName); ?>`?

Example that does not produce the problem.
```
<a href='javascript:void(0);' id='<?php echo $DeptID; ?>' onclick='changeDepartment("<?php echo $DeptID; ?>","`<?php echo str_replace("a", "\\ ", $DeptName); ?>`", "<?php echo $DeptShortName; ?>",1,"<?php echo $DeptState ?>");'>
  <span class="icon-office"></span>
  <?php echo $Pro_DeptName . ' TO '; ?>
</a>

<!-- ### BEGIN: Help Modal ### -->
<?php include_once $_SERVER['DOCUMENT_ROOT'] . "/shared/helpModal.php";  ?>
<!-- ### END: Help Modal ### -->
```

My concern is that `php-cs-fixer` breaks valid php / html code on save in this case. If this is a js-beautify issue can you help me open an issue with them so that we can get it fixed? I was not aware that php-cs-fixer was using js-beautify for the html beautification, so you might have more detail to provide to them to get this fixed.

**Comment by junstyle** [comment]
single quote in this parts : 

> str_replace("' ",

because this extension do html format first, and then run php-cs-fixer. so js-beautify can't format the code correctly.


you can test your code here: http://jsbeautifier.org/

```
<a href='javascript:void(0);' id='<?php echo $DeptID; ?>' onclick='changeDepartment("<?php echo $DeptID; ?>","<?php echo str_replace("'
  ", "\\ ", $DeptName); ?>  ", "<?php echo $DeptShortName; ?>",
  1, "<?php echo $DeptState ?>"); '>
                            <span class="icon-office"></span><?php echo $Pro_DeptName . ' TO '; ?>
                        </a>
                
<!-- ### BEGIN: Help Modal ### -->
<?php include_once $_SERVER['DOCUMENT_ROOT'] . "/shared/helpModal.php";  ?>
<!-- ### END: Help Modal ### -->
```

**Comment by esetnik** [comment]
Ok, that makes it clear. The issue is that the code we send to js-beautify needs to have php stripped out so that the formatting pass doesn't include code that is valid in php but not valid for js-beautify. Maybe it would be possible for this plugin to strip out code between php tags, then send to js-beautfiy, then reinsert the embedded php.

I did a bit of research and it looks like `js-beautify` is not officially supporting templated languages like php:
https://github.com/beautify-web/js-beautify/issues/688
https://github.com/beautify-web/js-beautify/issues/490
https://github.com/beautify-web/js-beautify/issues/532

And it looks like there was [an attempt to treat php tags as strings](https://github.com/beautify-web/js-beautify/commit/13b8031804315528414da35dea02332b687b412d), but I guess it doesn't work in this case.

**Comment by esetnik** [comment]
And also something you should track is the newly announced prettier plugin ecosystem, specifically https://github.com/prettier/plugin-php. Although they are currently very early on, maybe it would be viable to switch to using prettier since js-beautify seems to be untenable for html / js beautification of php. Currently prettier html support is not implemented, see https://github.com/prettier/prettier/issues/1882 for progress on that.
