### ISSUE TITLE
setting "php-cs-fixer.onsave" ignores finder config

### ISSUE THREAD

**Issue by qawsqs** [junstyle/vscode-php-cs-fixer#45]
.php_cs
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('myFolder')
    ->notPath('myFile.php')
    ->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true
    ])
    ->setFinder($finder);
```

When the vscode setting "php-cs-fixer.onsave" is set to true, it still formats files in `myFolder` and `myFile.php` in spite of finder config

**Comment by junstyle** [comment]
there is no relation between **php-cs-fixer.onsave** and your .php_cs

**Comment by qawsqs** [comment]
How do I exclude certain files from formatting then?

**Comment by junstyle** [comment]
php-cs-fixer.onsave  only format the current file.

```
    ->exclude('myFolder')
    ->notPath('myFile.php')
```

you can try the full path of the folder/file.

**Comment by qawsqs** [comment]
I don't quite understand.

Let's say we have two files: `myFile.php` and `vendor.php`.
I want `myFile.php` to be automatically fixed on save.
At the same time I want `vendor.php` not to be autofixed on save.

If it was JavaScript with ESLint, one could create an `.eslintignore` file with line `/vendor.php`.
How to do the same for this extension?

**Comment by junstyle** [comment]
### php-cs-fixer.onsave only format the **current** file. and did not format any other files.

you can test.

if you have other issues, you can go to [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) and open an issue.

**Comment by qawsqs** [comment]
> php-cs-fixer.onsave only format the current file. and did not format any other files.

I know.

What I want is to **not format** current file on save if it's name is `vendor.php`.
If I currently opened some other file I want it to be formatted on save.

**Comment by junstyle** [comment]
if you do not want format current file on save, you must set `"php-cs-fixer.onsave": false` and maybe set `"editor.formatOnSave": false`

**Comment by qawsqs** [comment]
If I wanted to that manually for each of hundreds of files, I wouldn't ask in the first place

**Comment by qawsqs** [comment]
Can be solved by adding `--path-mode=intersection`, e.g.
```bat
php-cs-fixer fix ./test.php --config=.php_cs --path-mode=intersection
```
So if `"editor.formatOnSave": true`, currently opened file will either be fixed on save or not depending on whether it is excluded in provided config file (`.php_cs`)

Reference: [PHP-CS-Fixer Usage section](https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage)

Is it possible to implement this argument?

**Comment by junstyle** [comment]
I had added the arg. --path-mode
you can update.
so late, I am little busy.
