### ISSUE TITLE
PHP CS Fixer: executablePath not found

### ISSUE THREAD

**Issue by Adorable-SkullMaster** [junstyle/vscode-php-cs-fixer#46]
![screenshot_2](https://user-images.githubusercontent.com/32746859/41734538-e94f3de4-75a4-11e8-9d1a-f30226a5aa13.png)

The extension is throwing me errors.

1. Installed using Composer. Successful. Found .bat file in `bin`.
2. PATH var: `C:\Users\{My Username}\AppData\Roaming\Composer\vendor\bin`
3. Set `"php-cs-fixer.executablePathWindows"`=`"php-cs-fixer.bat"` in settings

When I try to Fix the document it throws me
`PHP CS Fixer: executablePath not found, please check your settings. It will set to built-in php-cs-fixer.phar. Try again!`
I am on Windows 10.

**Comment by tyler36** [comment]
In Visual Code, my real username was used, I changed it to ```%username%``` for this post

**Comment by junstyle** [comment]
C:\Users\%username%\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.bat 
please confirm this file exist first

**Comment by tyler36** [comment]
Yes, ```C:\Users\%username%\AppData\Roaming\Composer\vendor\bin\php-cs-fixer.bat``` exists

I can run php-cs-fixer from the command line.
```php-cs-fixer -v``` =>  2.11.1

If I rename the above file to ```php-cs-fixer.boo```, it fails to output the version .

**Comment by junstyle** [comment]
if you can run from cmd, you can set 

"php-cs-fixer.executablePath": "php-cs-fixer.bat"

**Comment by tyler36** [comment]
```
"php-cs-fixer.executablePath": "php-cs-fixer.bat"
```
 works for me now.

I actually uninstalled / reinstalled the app to try with a fresh copy. It is working now though so thank you for you time.

Oh, and thanks for the extension. It makes me happy!
