### ISSUE TITLE
Consider supporting project relative paths for executable

### ISSUE THREAD

**Issue by ifeltsweet** [junstyle/vscode-php-cs-fixer#5]
In our project we prefer to install dev tools, including php-cs-fixer, via `composer require --dev`. This will place our executable under "./vendor/bin/php-cs-fixed" of our project root.

Could you consider supporting relative paths in `php-cs-fixer.executablePath`. It could use VS Code variables. Example:

```
"php-cs-fixer.executablePath": "${workspaceRoot}/vendor/bin/php-cs-fixer"
```

**Comment by junstyle** [comment]
ok, I had added this feature, you can update now.

2017-09-05 18:54 GMT+08:00 Denis Pshenov <notifications@github.com>:

**Comment by ifeltsweet** [comment]
You are amazing, that was so fast. Thank you so much.
