### ISSUE TITLE
Applying fixer on temp file with different name cause not working with risky rules 

### ISSUE THREAD

**Issue by Blum** [junstyle/vscode-php-cs-fixer#50]
Hello, I'm using the extension and it is working very well, except when using 'psr4'.
This rule is supposed to rename the class to match the file name.

The problem is that your extension is giving temporary file name, to apply the fixer on the code:
https://github.com/junstyle/vscode-php-cs-fixer/blob/d7b8e1be9aed912a249e800f396c0a6312663ef8/extension.js#L113

and so the rule 'psr4' can not be working. :disappointed: 

What about giving the temp file the same name like opened file:

`fileName = TmpDir +'/' + vscode.window.activeTextEditor.document.uri.fsPath.replace(/^.*[\\\/]/, '');`

This way it is all working. ?M

Thanks

**Comment by junstyle** [comment]
updated!

**Comment by Blum** [comment]
Thank you :smile:
