### ISSUE TITLE
Fix on save no longer working

### ISSUE THREAD

**Issue by garygreen** [junstyle/vscode-php-cs-fixer#51]
Seems since a recent VS Code update the "fix on save" config option no longer works. However running php cs fixer manually thru the command palette works

![image](https://user-images.githubusercontent.com/1702638/44864714-46485a80-ac78-11e8-8659-b49b1e3f720c.png)

**Comment by junstyle** [comment]
works on my vsc 1.26.1, windows.
you can disable the other extensions and test again. maybe conflict with it.

**Comment by timfeid** [comment]
Having this issue as well
