### ISSUE TITLE
javascript of ES Module is not formatted with formatHtml 

### ISSUE THREAD

**Issue by OHM79** [junstyle/vscode-php-cs-fixer#52]
windows 7
vscode 1.26.1
extension:php-cs-fixer 0.1.84

![default](https://user-images.githubusercontent.com/21155888/44901769-45302f80-ad43-11e8-80f8-96e2e96450d3.PNG)
![default](https://user-images.githubusercontent.com/21155888/44901776-46615c80-ad43-11e8-9700-1d8daf4cb12f.PNG)

**Comment by junstyle** [comment]
on my vsc
```
<script>
	import "sf"
	from "../lsf/js.js";
	(async () => {
		let v = 'ss'
	})();
</script>
```
format html by js-beautify, and vsc also use js-beautify to format html/js
https://github.com/beautify-web/js-beautify

some settings for formatting html:
"html.format.*   in settings.json

if you have touble you can issue at https://github.com/beautify-web/js-beautify
or you set formatHtml to false.
