### ISSUE TITLE
Can I use vendor/bin/php-cs-fixer for the executable?

### ISSUE THREAD

**Issue by ryanmortier** [junstyle/vscode-php-cs-fixer#54]
I've installed php-cs-fixer on a per-project basis via `composer require --dev friendsofphp/php-cs-fixer`

How can I have this extension use the `vendor/bin/php-cs-fixer` executable and also use my `.php_cs` file in the project root folder?

**Comment by junstyle** [comment]
executablePath can use ${workspaceRoot} as workspace root path.
