### ISSUE TITLE
PHP 7.3 Support

### ISSUE THREAD

**Issue by AndreasSchantl** [junstyle/vscode-php-cs-fixer#57]
Add support for PHP 7.3. Currently, a general error is shown when trying to format a PHP document.

![image](https://user-images.githubusercontent.com/9936988/49925591-b4c4c780-feb9-11e8-8945-76a45c24913a.png)

**Comment by Nothing-Works** [comment]
There is nothing to do with the Extension, it's [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer). It does not support php 7.3

**Comment by AndreasSchantl** [comment]
I see. Thank you for your response. Will close the issue then.

**Comment by Nothing-Works** [comment]
@AndreasSchantl are u on mac or windows? I think I found a temporary workaround for that. We can set the environment variables `PHP_CS_FIXER_IGNORE_ENV=1` for now, and change it back until they support 7.3.  Let me know if u still have trouble with it.

**Comment by robsontenorio** [comment]
@Nothing-Works  @AndreasSchantl where do you set this env var?

**Comment by neoighodaro** [comment]
> @Nothing-Works @AndreasSchantl where do you set this env var?

In your `.bash_profile` or equivalent. You would need to restart the shell session or in this case VSCode

```export PHP_CS_FIXER_IGNORE_ENV=1```

**Comment by AndreasSchantl** [comment]
> > @Nothing-Works @AndreasSchantl where do you set this env var?
> 
> 
> 
> In your `.bash_profile` or equivalent. You would need to restart the shell session or in this case VSCode
> 
> 
> 
> ```export PHP_CS_FIXER_IGNORE_ENV=1```

Sorry for the late reply. If you are using Laravel like me, you can find a phpunit.xml in which you can set or override certain environment variables. I did it there back then.
