### ISSUE TITLE
@Symfony and concat_space not correct.

### ISSUE THREAD

**Issue by michaelmano** [junstyle/vscode-php-cs-fixer#6]
When im using the following rules `"php-cs-fixer.rules": "@PSR2,@Symfony",` they are not being followed.
`return ' ' . $test . ' ';`
should be formatted to
`return ' '.$test.' ';`

When running `php-cs-fixer fix /path/to/file --rules=@PSR2,@Symfony` this works.

**Comment by junstyle** [comment]
if you want to use 
`"php-cs-fixer.rules": "@PSR2,@Symfony"`, 
first set 
`
_"php-cs-fixer.config": ""_
`
config file has high priority.

you can try.

**Comment by michaelmano** [comment]
This does nothing. even if i have a config with the correct setting. it still does not concat.

**Comment by junstyle** [comment]
settings like this:

> 
>     "php-cs-fixer.rules": "@PSR2,@Symfony",
>     "php-cs-fixer.config": "",

works fine!

**Comment by michaelmano** [comment]
```
 // PHP CS FORMATTER
"php-cs-fixer.executablePath": "/usr/local/Cellar/php-cs-fixer/2.3.2/php-cs-fixer",
"php-cs-fixer.onsave": true,
"php-cs-fixer.rules": "@PSR2,@Symfony",
"php-cs-fixer.config": "",
```
```
PHP CS Fixer 2.3.2 by Fabien Potencier and Dariusz Ruminski
```
```
Visual studio code Version 1.16.0 (1.16.0)
```
the spaces between the full stop, single comma and the variable are still not removed
`return ' ' . $test . ' ';`

If yours is the same I have another issue going on.

**Comment by junstyle** [comment]
what means "the spaces between the full stop"

if you config like this:
"php-cs-fixer.rules": "@PSR2,@Symfony",
"php-cs-fixer.config": "",

return ' ' . $test . ' ';
will be formatted to
return ' '.$test.' ';

I tested!

PHP CS Fixer 2.6.0 Local Tavern by Fabien Potencier and Dariusz Ruminski

**Comment by StefanNiederkofler** [comment]
@junstyle i have the same problem.

Config:
    "php-cs-fixer.rules": "@PSR2,@Symfony",
    "php-cs-fixer.config": "",
Set for User and Workspace

PHP CS Fixer 2.16.1 Yellow Bird
VSC 1.42.1

Test:
return ' '.$test.' ';
will be formatted always to
return ' ' . $test . ' ';
which is wrong

when running php-cs-fixer fix /path/to/file --rules=@PSR2,@Symfony it works.

Any suggestion what i could try?

@michaelmano Have you found a solution?
