### ISSUE TITLE
Weird behavior when pasting

### ISSUE THREAD

**Issue by VincentKos** [junstyle/vscode-php-cs-fixer#60]
Hello,

when I paste something and save this extension add all the code in my file where I pasted it (see this webm -> https://1drv.ms/u/s!AumlMZP9VNIugbxEZ7EhiH8DGWjPkQ )

Here is my .php_cs file : https://www.paste.org/96546

And here is my settngs for the extension : 

```json 
    "php-cs-fixer.executablePathWindows": "C:\\Users\\Vincent\\AppData\\Roaming\\Composer\\vendor\\bin\\php-cs-fixer.bat",
    "php-cs-fixer.onsave": true,
    "php-cs-fixer.config": "C:\\Users\\Vincent\\.php_cs",
```

**Comment by VincentKos** [comment]
it's not related to. It happen in all my file, no matter the project or file open.

**Comment by jorismak** [comment]
What happens is that vscode on paste seems to only give the pasted content to the formatter. So junstyle-php-cs-fixer writes a php file with just the pasted code, and calls php-cs-fixer on it.

But if php-cs-fixer is setup to always add a declare(strict_types=1); at the start (as an example), it will add that to every bit of pasted code.

Just cutting a line from a file, and repasting in that file on the same place will trigger this.
