### ISSUE TITLE
Extra declare strict types appears after every semicolon

### ISSUE THREAD

**Issue by JoelFeiner** [junstyle/vscode-php-cs-fixer#66]
If `declare_strict_types` setting is enabled and updating after every semi-colon is enabled, then typing a new line of code and entering a semi-colon will cause a line preceding the current line to appear so that you end up with this:

```
// some code
<?php declare(strict_types = 1);
$foo = 'bar';
// more code
```

The only way to fix this is to disable the extension, disable `declare_strict_types` or disable `php-cs-fixer.autoFixBySemicolon` in the VSCode settings.

**Comment by JoelFeiner** [comment]
This also happens when `php-cs-fixer.autoFixByBracket` is enabled.

Using version 0.1.93.

**Comment by junstyle** [comment]
please paste your source code, I test well on my vsc

**Comment by JoelFeiner** [comment]
@junstyle You can test this by starting with a file like this:

```
<?php

declare(strict_types = 1);

$foo = 'hello';
```

And then adding a new line with some code and typing a semi-colon at the end, with the `autoFixBySemicolon` flag turned on. I could reproduce this extremely reliably.

**Comment by junstyle** [comment]
![g](https://user-images.githubusercontent.com/3364972/51483842-f9a31e80-1dd4-11e9-810e-a1035cd11878.gif)

it's ok!

**Comment by olamedia** [comment]
`php-cs-fixer.autoFixBySemicolon` doesn't work with `Ctrl+V`, pasting `declare(strict_types = 1);` with a new line every time. simply typing does not cause this problem.

To check - paste something ending with a semicolon on non-empty line. 

Pasting `;` at the start of the line, inserts `<?php declare(strict_types=1);` with a new line
