### ISSUE TITLE
Running "php-cs-fixer: fix" doesn't respect config paths

### ISSUE THREAD

**Issue by Sergzy** [junstyle/vscode-php-cs-fixer#68]
Hello.

Running "php-cs-fixer: fix" from VSC results in "Paths from configuration file have been overridden by paths provided as command arguments." This eventually makes .php_cs defined paths useless and I have to run php_cs fixer manually from the command line instead of using this option directly from VSC.

Why doesn't it simply run the fix command in the opened directory (where it also found .php_cs)? This would also fix https://github.com/junstyle/vscode-php-cs-fixer/issues/49. Currently I have to edit .php_cs, if I want to make it working with this plugin.

Regards

**Comment by junstyle** [comment]
context menu on explorer, 'php-cs-fixer: fix' can format the files in the folder.
now when you run php-cs-fixer: fix from commandbox, if your openning file is not a php file, it will run fix without adding paths and the paths are from configuration file. if your openning file is a php file, it will fix the openning php file.
version: 0.1.95
