### ISSUE TITLE
command 'php-cs-fixer.fix' not found since 1.31 VSCode update

### ISSUE THREAD

**Issue by xelab** [junstyle/vscode-php-cs-fixer#69]
Hi,

I can't fix my files since I updated Visual Studio Code on version 1.31.1, this error is displayed when I I'm trying to fix my file : `command 'php-cs-fixer.fix' not found`

Here my informations about my system :

php cs fixer version : 0.1.95

Visual Studio Code:
Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Error details in the developer tools :
```
Error: command 'php-cs-fixer.fix' not found
    at Proxy.t._tryExecuteCommand (/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3226)
    at /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3225
```

**Comment by junstyle** [comment]
you can reinstall it, try

**Comment by xelab** [comment]
@junstyle I already tried to reinstall, even after delete the files, still got this error.

**Comment by junstyle** [comment]
how do you run the command to fix?

**Comment by xelab** [comment]
I run it either "on save" or with the command palette.
But I reinstalled completely Visual Studio Code today and now that's OK ! Don't know why... Thank you anyway!
