### ISSUE TITLE
Invalid behavior for autoFixBy*

### ISSUE THREAD

**Issue by JaPawel** [junstyle/vscode-php-cs-fixer#73]
Settings:

```
"php-cs-fixer.onsave": true,
"php-cs-fixer.autoFixByBracket": true,
"php-cs-fixer.autoFixBySemicolon": true,
```

.php_cs.dist:

```
<?php

declare(strict_types=1);

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        'declare_strict_types' => true,
    ])
;
```

Starting point:

<img width="266" alt="1" src="https://user-images.githubusercontent.com/8151020/54359728-9494d800-4663-11e9-9614-a3359189f2b5.png">

then type `;`

<img width="255" alt="2" src="https://user-images.githubusercontent.com/8151020/54359816-c27a1c80-4663-11e9-9729-f7b5cad1fd68.png">

Starting point:

<img width="332" alt="3" src="https://user-images.githubusercontent.com/8151020/54359899-e5a4cc00-4663-11e9-823d-448711eb92d5.png">

then type `}`

<img width="322" alt="4" src="https://user-images.githubusercontent.com/8151020/54359898-e50c3580-4663-11e9-989a-b8b3d5f240a9.png">

**Comment by junstyle** [comment]
try new version now !

**Comment by JaPawel** [comment]
@junstyle thanks. I can confirm that `declare(strict_types=1);` is not added and code does not disappear, but not sure does formatting work after `;` is typed. For example:

```
    public function test()
    {
$a = 'aa'
    }
```

type `;` - and nothing happens.

But for:

```
public function test()
    {
$a = 'aa';
```

type `}` and it works:

```
    public function test()
    {
        $a = 'aa';
    }
```

**Comment by junstyle** [comment]
not add indent to the single line code after type ";".
only format the code of the line code.
it's complex to judge。

**Comment by JaPawel** [comment]
Ok, only format for single line makes sense. 
Thanks for fix.
