### ISSUE TITLE
Autoformating onSave for larger files

### ISSUE THREAD

**Issue by JaPawel** [junstyle/vscode-php-cs-fixer#75]
Not sure is its by design or a bug, but when file has like 600 lines or more, then autoformating onsave does not work.

I have file with many properties, and getters and setters - hitting save does not fire auto format, I have to manually run command. 
When removed half of setters/getters hitting save runs auto format.

**Comment by junstyle** [comment]
when run php-cs-fixer over a period of time, vscode cancel the operation.
so autoformat onsave is failed.
it maybe performance issue.

**Comment by JaPawel** [comment]
Oh, I get it. Maybe new setting option to show warning in status bar when that situation happens (if its possible to do something quick after vscode cancel long running operation) or show messages/logs in output window?
