### ISSUE TITLE
Some of .php_cs file rules make plugin fails

### ISSUE THREAD

**Issue by lycwed** [junstyle/vscode-php-cs-fixer#79]
In your example of .php_cs file 
-> ```'array_indentation' => true,``` generate this error with the fixer : The rules contain unknown fixers: "array_indentation".

-> ```'self_accessor' => true,``` generate this error with the fixer : The rules contain risky fixers (self_accessor), but they are not allowed to run. Perhaps you forget to use --allow-risky option? (however I allow risky in the plugin options)

When I comment / remove these 2 rules your plugin is just running like a charm!

**Comment by junstyle** [comment]
I think you should go to  https://github.com/FriendsOfPHP/PHP-CS-Fixer , and see how to use the rules.

**Comment by lycwed** [comment]
I go on this website, I see that the 2 rules exists but when I launch directly `php-cs-fixer` command from my terminal on my php folder (package install like it's explained), with your default config it fails with these errors in the terminal, that's why I send you that because if it happens to me it has happens for someone else, the goal for me is just to say to you becareful and make your plugin be the best!
