### ISSUE TITLE
Format selection fails if there are linting errors

### ISSUE THREAD

**Issue by ifeltsweet** [junstyle/vscode-php-cs-fixer#8]
If you attempt to format a method inside class it will fail. That is because php-cs-fixer will abort because of linting errors. This is understandable because we only provided part of our code to php-cs-fixer and it doesn't see the rest of context.

Is there a way to provide the whole context to php-cs-fixer but only apply fixes to specific lines?

**Comment by keradus** [comment]
you could fix whole file, grab diff in udiff format from PHP CS Fixer and then apply only part of generated patch.
be warned that behaviour of this could be tricky, if your rules are configured to, for example, move whole method to different place (Eg private methods to bottom of class)

**Comment by bfranklyn** [comment]
wow what an awkward workaround ...
