### ISSUE TITLE
[exthost] [error] [junstyle.php-cs-fixer] provider FAILED

### ISSUE THREAD

**Issue by homerjam** [junstyle/vscode-php-cs-fixer#80]
Out of the blue I get this error when trying to use this plugin - I've tried using the bundled phar and brew/composer versions of php-cs-fixer. I'm not sure what else to try??

```
[2019-04-29 15:10:22.377] [exthost] [error] [junstyle.php-cs-fixer] provider FAILED
```

**Comment by junstyle** [comment]
if you don't know how to config, nothing to do, it will use internal php-cs-fixer.phar.
