### ISSUE TITLE
invalid PHP problem regarding end }

### ISSUE THREAD

**Issue by MircoBabin** [junstyle/vscode-php-cs-fixer#81]
Also filed under https://github.com/Microsoft/vscode/issues/73074. According to VS Code this is a problem with the extension.

Visual Studio code reports an invalid problem in PHP code. An end brace } should be missing. This is not true however.

Version: 1.33.1 (system setup)
Commit: 51b0b28
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Name: php cs fixer
Id: junstyle.php-cs-fixer
Description: PHP CS Fixer extension for VS Code, php formatter, php code beautify tool, format html
Version: 0.1.118
Publisher: junstyle
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=junstyle.php-cs-fixer

Steps to Reproduce:

* Store attached [404.txt](https://github.com/junstyle/vscode-php-cs-fixer/files/3133921/404.txt) as 404.php
* Open 404.php in VS Code
* A problem will be reported, see also attached screenshot
![screenshot](https://user-images.githubusercontent.com/8981285/57008344-b1737380-6bef-11e9-9962-6d96b99858b6.png)

Does this issue occur when all extensions are disabled?: No

**Comment by junstyle** [comment]
![image](https://user-images.githubusercontent.com/3364972/57176546-d97f0300-6e8b-11e9-8426-a61af48037fa.png)

this is my code formatted by the extension

what's your result after formatted?

maybe your php.ini has not set the shorttag to true.

the syntax validate tool can't work well

it's unrelated to the extension, so I will close the issue
