### ISSUE TITLE
Allow short function imports

### ISSUE THREAD

**Issue by dugajean** [junstyle/vscode-php-cs-fixer#84]
There should be a configuration that allows to toggle between short and long function imports. Short function imports are PSR2 compliant.

For example this code:

```php
use function MyNamespace\Helpers\{
    color,
    slash,
    ends_with,
    comma_list,
    snake_case,
    starts_with,
    current_path
};
```

Turns into

```php
use function MyNamespace\Helpers\color;
use function MyNamespace\Helpers\slash;
use function MyNamespace\Helpers\ends_with;
use function MyNamespace\Helpers\comma_list;
use function MyNamespace\Helpers\snake_case;
use function MyNamespace\Helpers\starts_with;
use function MyNamespace\Helpers\current_path;
```

And I don't want that. This forces me to disable the extension on save. Please consider fixing this.

**Comment by junstyle** [comment]
about the rules please reference https://github.com/FriendsOfPHP/PHP-CS-Fixer
this extension just get result from php-cs-fixer
