### ISSUE TITLE
onsave not working

### ISSUE THREAD

**Issue by vigovigo** [junstyle/vscode-php-cs-fixer#85]
After vscode upgrade to 1.34.0，`onsave` doesn't work； but right click and then `format Document` works fine； and `editor.formatOnPaset` works fine;

here is part of my settings;

```
"editor.formatOnSave": true,
"php-cs-fixer.onsave": true,
"[php]": {
    "editor.defaultFormatter": "junstyle.php-cs-fixer",
    "editor.formatOnSave": true
},
```

**Comment by junstyle** [comment]
please show me the logs from developer tools

**Comment by vigovigo** [comment]
> please show me the logs from developer tools

![image](https://user-images.githubusercontent.com/2811986/58305371-61708100-7e2a-11e9-9380-5793070208ee.png)

**Comment by junstyle** [comment]
from the log you can see "aborted format on save after 750ms"
maybe your pc performance problem, run the php-cs-fixer cost too much time, so it aborted.
and maybe your php file is too large.

**Comment by vigovigo** [comment]
Now solved this by adding `"editor.formatOnSaveTimeout": 1250` to the settings;

**Comment by vigovigo** [comment]
Thank you for reminding me to check out the developer tools. 😄

**Comment by junstyle** [comment]
yeah, good, I don't know this setting yet.
