### ISSUE TITLE
[Future request] Information about error in status bar

### ISSUE THREAD

**Issue by kanlukasz** [junstyle/vscode-php-cs-fixer#86]
Hey,

I would like to ask about the possibility of adding an additional feature that will inform you that CS Fixer has not completed the task or is an error.

For example:
![obraz](https://user-images.githubusercontent.com/30685349/58798305-91760c00-8602-11e9-82fd-08efc1b672ca.png)

I am asking about this because when there is a syntax problem (eg. forgotten semicolon or parenthesis) the formatting is not done and nothing happened - user does not get any information about it.

Lack of this information causes confusion - I do not know if the plugin has stopped working or if the formatting is not done just for some reason.

Information about the correct formatting of the document would also be welcomed.

I know about `OUTPUT Log (Extension Host)` next to `PROBLEMS` but it's not the same and checking it every time is not very convenient

What do you think about it?
Is it possible?

**Comment by ridvanaltun** [comment]
Thats seems be a nice feature. +1

**Comment by kanlukasz** [comment]
It's always nice to see why the issue has been closed.......
