### ISSUE TITLE
executiblePath does not support folder names with spaces

### ISSUE THREAD

**Issue by rtaylo10** [junstyle/vscode-php-cs-fixer#88]
Hello,

I've recently encountered an issue when using Windows 10 where the cs fixer cannot find an executiblePath if it contains spaces. 

In my settings file I have the following setting:
"php-cs-fixer.executiblePath": 
"C:\\Users\\Work Profile\\Documents\\Projects\\projects\\project1\\vendor\\bin\\php-cs-fixer",

When I try to format, I get "PHP CS Fixer: php general error.", and in developer tools there is a message with "[Extension Host] 'C:\Users\Work' is not recognized as an internal or external command, operable program or batch file.". I'm assuming that this is an issue with parsing the file path, since I have other extensions that use similar pathing and don't run into this issue. 

Is there any way to fix this?

**Comment by junstyle** [comment]
no problem when spaces in folder names

are you sure setting like this:

> "php-cs-fixer.executiblePath": "C:\Users\Work Profile\Documents\Projects\projects\project1\vendor\bin\php-cs-fixer",

I think you should use double backlash

"php-cs-fixer.executiblePath": "C:\\Users\\Work Profile\\Documents\\Projects\\projects\\project1\\vendor\\bin\\php-cs-fixer"

or 

"php-cs-fixer.executiblePath": "C:/Users/Work Profile/Documents/Projects/projects/project1/vendor/bin/php-cs-fixer"

**Comment by rtaylo10** [comment]
I've been playing around with it and re-installed VSCode, and it seems to be working fine for me now. Trying to reproduce the issue again since I had tried every possible format of the file path before, but it's working fine, so it must have been an error on my part.
