### ISSUE TITLE
Ubuntu 18.04 executablePath not found

### ISSUE THREAD

**Issue by tipytechnique** [junstyle/vscode-php-cs-fixer#91]
Hi, i have an issue, and i didn't find a solution that works for me on existing issues.

I'm on Ubuntu 18.04 and i have installed `php-cs-fixer` from composer.
`php-cs-fixer` works well in command line.

For example i can run this without issue :
`php-cs-fixer fix --config=./.php_cs.dist --path-mode=intersection ./`

Here are my VSCode settings : 
```
"php-cs-fixer.formatHtml": true,
"php-cs-fixer.lastDownload": 0,
"php-cs-fixer.onsave": true,
"php-cs-fixer.pathMode": "intersection",
"[php]": {
    "editor.defaultFormatter": "junstyle.php-cs-fixer"
},
"php-cs-fixer.executablePath": "php-cs-fixer",
```
When i'm saving a file, the console developer show me this error : 
![error_php_cs_fixer](https://user-images.githubusercontent.com/44948849/60279834-17375f80-9902-11e9-900d-0162d927722d.png)

How can i made your plugin works ?

**Comment by junstyle** [comment]
which php-cs-fixer

**Comment by tipytechnique** [comment]
I ran this `composer global require friendsofphp/php-cs-fixer`

**Comment by junstyle** [comment]
run   ` which php-cs-fixer', and   `which php`
php must in  bin dirs.

**Comment by tipytechnique** [comment]
```
➜  ~ which php-cs-fixer
/home/yayo/.composer/vendor/bin/php-cs-fixer
➜  ~ which php
/usr/bin/php
```
Should i move `php-cs-fixer` to the `/usr/bin` so ?

**Comment by junstyle** [comment]
try full path:
`"php-cs-fixer.executablePath": "/home/yayo/.composer/vendor/bin/php-cs-fixer",`

**Comment by tipytechnique** [comment]
Working now, thx :+1:
