### ISSUE TITLE
Format php file cannot be executed

### ISSUE THREAD

**Issue by zeroidentidad** [junstyle/vscode-php-cs-fixer#95]
When try Ctrl+Shift+I nothing happend, only get "Cannot read property 'on' of undefined"

In vscode repo a vscodebot reply:
"This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the marketplace for VS Code. See also our issue reporting guidelines."

VS Code version: Code 1.37.0 (036a6b1, 2019-08-08T01:24:14.598Z)
OS version: Linux x64 4.15.0-55-generic

**Comment by junstyle** [comment]
please paste your developer tools logs

**Comment by zeroidentidad** [comment]
![captura_1](https://user-images.githubusercontent.com/2924638/62997518-33e61300-be2e-11e9-88e3-331e329ef3d9.png)

**Comment by junstyle** [comment]
/opt/lappstack7127/php/bin ?  access deny?

**Comment by zeroidentidad** [comment]
Thanks by feeback.

I get a fix, doing as follow:

1- add php executable path in **/ect/environment**

2- remove **"php.validate.executablePath"** line on _settings.json_ file of vscode configuration
