### ISSUE TITLE
Comment block closing tags are sometimes formatted as HTML comment closing tags

### ISSUE THREAD

**Issue by wlarch** [junstyle/vscode-php-cs-fixer#96]
**Problem**
Comment block closing tags are sometimes formatted as HTML comment closing tags.

**When**
When I execute the "fix this file" function on one of our Controller :

![image](https://user-images.githubusercontent.com/5958500/63172862-a1e83100-c00c-11e9-9b84-f81c684033f7.png)

When I execute the "diff" function, I cannot see this replacement in the result :

![image](https://user-images.githubusercontent.com/5958500/63173156-3ce10b00-c00d-11e9-93c0-07baa9205fc4.png)

Doe it mean the problem would be caused by another plugin ?
Why would this happen and how can I fix it ?

Thanks

**Comment by junstyle** [comment]
fix is diffirenet with diff, diff not format html.
fix can format html
but I test the code, it's ok, can you show me more your codes, and html together.

**Comment by junstyle** [comment]
thanks, new version fixed the bug

**Comment by wlarch** [comment]
Thank you so much!
