### ISSUE TITLE
Avoid using workspace.rootPath

### ISSUE THREAD

**Issue by roblourens** [junstyle/vscode-php-cs-fixer#98]
This extension appears to be using the `workspace.rootPath` API. This is a deprecated property and may not work as expected. Please use `workspaceFolders` instead. More info:  https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#eliminating-rootpath

https://github.com/microsoft/vscode/issues/69335

**Comment by junstyle** [comment]
```
        if (workspace.rootPath != undefined) {
            this.executablePath = this.executablePath.replace('${workspaceRoot}', workspace.rootPath);
        }
```

I checked , only those codes using workspace.rootPath, it's ok if workspace.rootPath deprecated

**Comment by simioluwatomi** [comment]
I was about to open a new issue regarding this. I really think the extension should be updated to reflect the changes in VS Code's variable reference docs.
