### ISSUE TITLE
Cannot format code inside of switch statement

### ISSUE THREAD

**Issue by TonyGravagno** [junstyle/vscode-php-cs-fixer#99]
I've seen other notes in this repo about issues that look similar to this, but I haven't found a solution. Consider this first code segment (intentionally not indented:

```php
<?php
function myfunc($atts)
{
global $foo;
$test = 1;
switch ($test) {
case 1:
          $test = 2;
break;
default:
break;
}
$test = 3;
}

```

Now format it to get this:

```php
<?php
function myfunc($atts)
{
    global $foo;
    $test = 1;
    switch ($test) {
case 1:
          $test = 2;
break;
default:
break;
}
    $test = 3;
}
``` 

Note that nothing within the switch (condition) { x } braces changes, but the line following the switch final brace does indent. Any ideas?

Some details:
Windows 8.1
VS Code 1.37.1
php-c-fixer 0.1.121
PHP IntelliSense2.3.10 (Becker)

settings.json :

```json
    "php-cs-fixer.executablePath": "C:\\php\\php-cs-fixer.phar",
    "[php]": {
        "editor.defaultFormatter": "junstyle.php-cs-fixer"
    },
    "php.suggest.basic": false,
```

Relevant my.code-workspace:

```json
	"settings": {
		"phpcs.showSources": true,
		"phpcs.standard": "C:\\php\\pear\\PHP\\CodeSniffer\\tg_wp_php_ruleset.xml",
		"phpcs.showWarnings": true, 
		"phpcs.warningSeverity": 1,     ; * testing linting
		"phpcs.errorSeverity": 1,          ; * testing linting
		"php-cs-fixer.rules": "@PSR2",
		"php.suggest.basic": false,
		"php.validate.enable": false,
		"phpcs.autoConfigSearch": false,
		"phpcs.trace.server": "verbose",
		"php-cs-fixer.autoFixByBracket": false,
		"php-docblocker.useShortNames": true
	}
```

With a complex ruleset, Code Sniffer does not report any errors with the PHP above. No error/warnings logged. But still no formatting.
With a simpleruleset, many errors are flagged about spacing, but no functional issues.

I hope formatting doesn't throw an exception when a linting error is found. Part of the purpose of formatting is to fix some linting issues. I am eager to try diagnostics. My goal is simply to find a configuration that allows me to lint and format/fix.

Thanks!

**Comment by junstyle** [comment]
you can run php-cs-fixer cmd on a terminal. and see whether can format switch.
formatting issue please go to : https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by TonyGravagno** [comment]
The problem here is that I've been confusing PHP_CodeSniffer and PHP-CS-Fixer. :face_with_head_bandage:
